// Generated by HiveVM CC v.1.0 - Do not edit this line!

package org.hivevm.cc.parser;

/**
 * Token literal values and constants. Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface ParserConstants {

    // End of File
    int EOF = 0;

    // RegularExpression Ids
    int _LOOKAHEAD = 1;
    int _IGNORE_CASE = 2;
    int _PARSER = 3;
    int _TOKEN = 4;
    int _SPECIAL_TOKEN = 5;
    int _MORE = 6;
    int _SKIP = 7;
    int _RULE = 8;
    int _EOF = 9;
    int SINGLE_LINE_COMMENT = 18;
    int MULTI_LINE_COMMENT = 19;
    int ECODE_END = 20;
    int ECODE_DATA = 21;
    int BOOLEAN = 23;
    int INT = 24;
    int CHAR = 25;
    int NULL = 26;
    int TRUE = 27;
    int FALSE = 28;
    int INTEGER_LITERAL = 29;
    int DECIMAL_LITERAL = 30;
    int HEX_LITERAL = 31;
    int OCTAL_LITERAL = 32;
    int FLOATING_POINT_LITERAL = 33;
    int DECIMAL_FLOATING_POINT_LITERAL = 34;
    int DECIMAL_EXPONENT = 35;
    int HEXADECIMAL_FLOATING_POINT_LITERAL = 36;
    int HEXADECIMAL_EXPONENT = 37;
    int CHARACTER_LITERAL = 38;
    int STRING_LITERAL = 39;
    int LPAREN = 40;
    int RPAREN = 41;
    int LBRACE = 42;
    int RBRACE = 43;
    int LBRACKET = 44;
    int RBRACKET = 45;
    int COMMA = 46;
    int ASSIGN_OP = 47;
    int SEMICOLON = 48;
    int DOT = 49;
    int ASSIGN = 50;
    int GT = 51;
    int LT = 52;
    int BANG = 53;
    int TILDE = 54;
    int HOOK = 55;
    int HASH = 56;
    int COLON = 57;
    int PLUS = 58;
    int MINUS = 59;
    int STAR = 60;
    int BIT_OR = 61;
    int IDENTIFIER = 62;
    int LETTER = 63;
    int PART_LETTER = 64;

    // Lexical states
    int DEFAULT = 0;
    int IN_SINGLE_LINE_COMMENT = 1;
    int IN_MULTI_LINE_COMMENT = 2;
    int PARSER_CODE = 3;

    // Literal token values
    String[] tokenImage = {
        "<EOF>",
        "\"LOOKAHEAD\"",
        "\"IGNORE_CASE\"",
        "\"PARSER\"",
        "\"TOKEN\"",
        "\"SPECIAL_TOKEN\"",
        "\"MORE\"",
        "\"SKIP\"",
        "\"RULE\"",
        "\"EOF\"",
        "\" \"",
        "\"\\t\"",
        "\"\\n\"",
        "\"\\r\"",
        "\"\\f\"",
        "\"//\"",
        "\"/*\"",
        "\"<?\"",
        "<SINGLE_LINE_COMMENT>",
        "\"*/\"",
        "\"?>\"",
        "<ECODE_DATA>",
        "<token of kind 22>",
        "\"boolean\"",
        "\"int\"",
        "\"char\"",
        "\"null\"",
        "\"true\"",
        "\"false\"",
        "<INTEGER_LITERAL>",
        "<DECIMAL_LITERAL>",
        "<HEX_LITERAL>",
        "<OCTAL_LITERAL>",
        "<FLOATING_POINT_LITERAL>",
        "<DECIMAL_FLOATING_POINT_LITERAL>",
        "<DECIMAL_EXPONENT>",
        "<HEXADECIMAL_FLOATING_POINT_LITERAL>",
        "<HEXADECIMAL_EXPONENT>",
        "<CHARACTER_LITERAL>",
        "<STRING_LITERAL>",
        "\"(\"",
        "\")\"",
        "\"{\"",
        "\"}\"",
        "\"[\"",
        "\"]\"",
        "\",\"",
        "\"::=\"",
        "\";\"",
        "\".\"",
        "\"=\"",
        "\">\"",
        "\"<\"",
        "\"!\"",
        "\"~\"",
        "\"?\"",
        "\"#\"",
        "\":\"",
        "\"+\"",
        "\"-\"",
        "\"*\"",
        "\"|\"",
        "<IDENTIFIER>",
        "<LETTER>",
        "<PART_LETTER>"
    };
}

// Checksum=52D6A2370AAE6E9DAB938EC642E764D7 (Do not edit this line!)
// Options: JAVA_PACKAGE='org.hivevm.cc.parser', PRODUCTIONS=64, PRODUCTIONS_LABEL, STATES=4, STATES_INDEX, STATES_NAME, TOKENS=55, TOKENS_LABEL, TOKENS_ORDINAL
