// Generated by HiveVM CC v.1.0 - Do not edit this line!

package org.hivevm.cc.parser;

import java.util.List;
import java.util.ArrayList;
import org.hivevm.cc.model.*;

public class Parser
    extends AbstractJavaCCParser
    implements ParserConstants {

/************************************************
 * THE JAVACC GRAMMAR SPECIFICATION STARTS HERE *
 ************************************************/
  public final void javacc_input() throws ParseException {
    jj_consume_token(_PARSER);
    jj_consume_token(LPAREN);
    option_binding();
    label_1:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case COMMA:{
        ;
        break;
        }
      default:
        jj_la1[0] = jj_gen;
        break label_1;
      }
      jj_consume_token(COMMA);
      option_binding();
    }
    jj_consume_token(RPAREN);
    label_2:
    while (true) {
      bnf_production();
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case _RULE:{
        ;
        break;
        }
      default:
        jj_la1[1] = jj_gen;
        break label_2;
      }
    }
    label_3:
    while (true) {
      regular_expr_production();
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case _TOKEN:
      case _SPECIAL_TOKEN:
      case _MORE:
      case _SKIP:
      case LT:{
        ;
        break;
        }
      default:
        jj_la1[2] = jj_gen;
        break label_3;
      }
    }
    jj_consume_token(0);
}


  public final void option_binding() throws ParseException {
 Token t; 
    t = jj_consume_token(IDENTIFIER);
    jj_consume_token(COLON);
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case INTEGER_LITERAL:{
      IntegerLiteral();
      break;
      }
    case TRUE:
    case FALSE:{
      BooleanLiteral();
      break;
      }
    case STRING_LITERAL:{
      StringLiteral();
      break;
      }
    default:
      jj_la1[3] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
 setInputOption(t, getToken(0)); 
}


  public final void bnf_production() throws ParseException {

    var t = getToken(1);
    var c = new Container();
    var p = new BNFProduction();
    p.setFirstToken(t);
    p.setThrowsList(new ArrayList<>());
    p.setLocation(t);

    jj_consume_token(_RULE);

    p.setLhs(identifier());

    FormalParameters(p.getParameterListTokens());
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case COLON:{
      jj_consume_token(COLON);
      Type();
 p.setReturnTypeToken(getToken(0)); 
      break;
      }
    default:
      jj_la1[4] = jj_gen;
      ;
    }
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case HASH:{
      node_descriptor(p, p);
      break;
      }
    default:
      jj_la1[5] = jj_gen;
      ;
    }
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case ECODE_DATA:{
      jj_consume_token(ECODE_DATA);
 p.addDeclaration(getToken(0)); 
      jj_consume_token(ECODE_END);
      break;
      }
    default:
      jj_la1[6] = jj_gen;
      ;
    }
    jj_consume_token(ASSIGN_OP);
    expansion_choices(c, p);
    jj_consume_token(RBRACE);
    t = jj_consume_token(SEMICOLON);
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case ECODE_DATA:{
      jj_consume_token(ECODE_DATA);
 p.addDeclarationEnd(getToken(0)); 
      jj_consume_token(ECODE_END);
      break;
      }
    default:
      jj_la1[7] = jj_gen;
      ;
    }

    p.setLastToken(t);
    production_addexpansion(p, c.get());
    addproduction(p);

}


  public final void regular_expr_production() throws ParseException {

    List<String> states;
    var t = getToken(1);
    var p = new TokenProduction();
    p.setFirstToken(t);
    p.setLocation(t);
    // set p.lexStates assuming there is no state spec.
    // and then override if necessary.
    p.setLexStates(new String[] {"DEFAULT"});

    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case LT:{
      if (jj_2_1(2)) {
        jj_consume_token(LT);
        jj_consume_token(STAR);
        jj_consume_token(GT);
 p.setLexStates(null); 
      } else {
        switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
        case LT:{
          jj_consume_token(LT);
 states = new ArrayList<>(); 
          t = jj_consume_token(IDENTIFIER);
 states.add(t.image); 
          label_4:
          while (true) {
            switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
            case COMMA:{
              ;
              break;
              }
            default:
              jj_la1[8] = jj_gen;
              break label_4;
            }
            jj_consume_token(COMMA);
            t = jj_consume_token(IDENTIFIER);
 states.add(t.image); 
          }
          jj_consume_token(GT);

	  p.setLexStates(new String[states.size()]);
	  for (int i = 0; i < states.size(); i++)
	    p.setLexState((String)states.get(i), i);

          break;
          }
        default:
          jj_la1[9] = jj_gen;
          jj_consume_token(-1);
          throw new ParseException();
        }
      }
      break;
      }
    default:
      jj_la1[10] = jj_gen;
      ;
    }
    regexpr_kind(p);
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case LBRACKET:{
      jj_consume_token(LBRACKET);
      t = jj_consume_token(_IGNORE_CASE);
      jj_consume_token(RBRACKET);
 p.setIgnoreCase(true); 
      break;
      }
    default:
      jj_la1[11] = jj_gen;
      ;
    }
    jj_consume_token(ASSIGN_OP);
    regexpr_spec(p);
    label_5:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case BIT_OR:{
        ;
        break;
        }
      default:
        jj_la1[12] = jj_gen;
        break label_5;
      }
      jj_consume_token(BIT_OR);
      regexpr_spec(p);
    }
    t = jj_consume_token(SEMICOLON);
 addregexpr(p); 
}


  public final void regexpr_kind(TokenProduction p) throws ParseException {
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case _TOKEN:{
      jj_consume_token(_TOKEN);
 p.setKind(TokenProduction.Kind.TOKEN); 
      break;
      }
    case _SPECIAL_TOKEN:{
      jj_consume_token(_SPECIAL_TOKEN);
 p.setKind(TokenProduction.Kind.SPECIAL); 
      break;
      }
    case _SKIP:{
      jj_consume_token(_SKIP);
 p.setKind(TokenProduction.Kind.SKIP); 
      break;
      }
    case _MORE:{
      jj_consume_token(_MORE);
 p.setKind(TokenProduction.Kind.MORE); 
      break;
      }
    default:
      jj_la1[13] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
}


  public final void regexpr_spec(TokenProduction p) throws ParseException {

    var c = new Container();
    var a = new Action();
    Token t = null;

    regular_expression(c);

    var res = new RegExprSpec(c.get());
    res.rexp.setTpContext(p);

    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case ECODE_DATA:
    case LBRACE:{
 t = getToken(1); 
      Statement(a.getActionTokens());

	  if (res.rexp.isPrivateExp())
	    JavaCCErrors.parse_error(t, "Actions are not permitted on private (#) regular expressions.");

      break;
      }
    default:
      jj_la1[14] = jj_gen;
      ;
    }
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case COLON:{
      jj_consume_token(COLON);
      t = jj_consume_token(IDENTIFIER);

	  res.nextState = t.image;
	  if (res.rexp.isPrivateExp())
	    JavaCCErrors.parse_error(t, "Lexical state changes are not permitted after private (#) regular expressions.");

      break;
      }
    default:
      jj_la1[15] = jj_gen;
      ;
    }

	  res.act = a;
	  res.nsTok = t;
	  p.getRespecs().add(res);

}


  public final void expansion_choices(Container c1, BNFProduction p) throws ParseException {

    var morethanone = false;
    var c2 = new Container();
    Choice ch = null; // unnecessary initialization to make Java compiler happy!

    expansion(c1, p);
    label_6:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case BIT_OR:{
        ;
        break;
        }
      default:
        jj_la1[16] = jj_gen;
        break label_6;
      }
      jj_consume_token(BIT_OR);
      expansion(c2, p);

	  if (morethanone) {
	    Expansion exp = c2.get();
	    ch.getChoices().add(exp);
	    exp.setParent(ch);
	  } else {
	    morethanone = true;
	    Expansion exp = c1.get();
	    ch = new Choice();
	    ch.setLocation(exp);
	    ch.getChoices().add(exp);
	    exp.setParent(ch);

	    exp = c2.get();
      ch.getChoices().add(exp);
	    exp.setParent(ch);
	  }

    }

	  if (morethanone)
	    c1.set(ch);

}


  public final void expansion(Container c1, BNFProduction p) throws ParseException {

    Expansion exp = null;
    var t = getToken(1);
    var c2 = new Container();
    var seq = new Sequence();
    seq.setLocation(t);
    var la = new Lookahead();
    la.setLocation(t);
    la.setAmount(getOptions().getLookahead());
    la.setLaExpansion(null);
    la.setExplicit(false);

    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case _LOOKAHEAD:{
      t = jj_consume_token(_LOOKAHEAD);
      jj_consume_token(LPAREN);
      la = local_lookahead(p);
      jj_consume_token(RPAREN);

	  if (inLocalLA != 0 && la.getAmount() != 0)
	    JavaCCErrors.warning(t, "Only semantic lookahead specifications within other lookahead specifications is considered.  Syntactic lookahead is ignored.");
	
      break;
      }
    default:
      jj_la1[17] = jj_gen;
      ;
    }

    seq.getUnits().add(la);

    label_7:
    while (true) {
      expansion_unit(c2, p);

    exp = c2.get();
	  seq.getUnits().add(exp);
	  exp.setParent(seq, seq.getUnits().size() - 1);

      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case HASH:{
        node_descriptor(exp, p);
        break;
        }
      default:
        jj_la1[18] = jj_gen;
        ;
      }
      if (notTailOfExpansionUnit()) {
        ;
      } else {
        break label_7;
      }
    }

    if (la.getLaExpansion() == null)
      la.setLaExpansion(seq);
    c1.set(seq);

}


  public final                                         Lookahead local_lookahead(BNFProduction p) throws ParseException {

    var la = new Lookahead();
    la.setExplicit(true);
    la.setLaExpansion(null);
    la.setLocation(getToken(1));
    var c = new Container();
    boolean commaAtEnd = false;
    boolean emptyLA = true;
    int laAmount;
    inLocalLA++;

    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case INTEGER_LITERAL:{
      laAmount = IntegerLiteral();

    emptyLA = false;
    la.setAmount(laAmount);

      break;
      }
    default:
      jj_la1[19] = jj_gen;
      ;
    }
    if (checkEmptyLA(emptyLA, getToken(1))) {
      jj_consume_token(COMMA);
 commaAtEnd = true; 
    } else {
      ;
    }
    if (checkEmpty(getToken(1))) {
      expansion_choices(c, p);

	  emptyLA = false; commaAtEnd = false;
	  la.setLaExpansion(c.get());

    } else {
      ;
    }
    if (checkEmptyLAAndCommandEnd(emptyLA, commaAtEnd, getToken(1))) {
      jj_consume_token(COMMA);
 commaAtEnd = true; 
    } else {
      ;
    }
    if (checkEmptyLAOrCommandEnd(emptyLA, commaAtEnd)) {
      jj_consume_token(LBRACE);
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case _LOOKAHEAD:
      case _IGNORE_CASE:
      case _PARSER:
      case _TOKEN:
      case _SPECIAL_TOKEN:
      case _MORE:
      case _SKIP:
      case _EOF:
      case NULL:
      case TRUE:
      case FALSE:
      case INTEGER_LITERAL:
      case FLOATING_POINT_LITERAL:
      case CHARACTER_LITERAL:
      case STRING_LITERAL:
      case LPAREN:
      case IDENTIFIER:{
        Expression(la.getActionTokens());
        break;
        }
      default:
        jj_la1[20] = jj_gen;
        ;
      }
      jj_consume_token(RBRACE);

	  if (emptyLA)
	    la.setAmount(0);

    } else {
      ;
    }

	  inLocalLA--;
	  return la;

}


  public final void expansion_unit(Container c, BNFProduction p) throws ParseException {

    String name;
    List<Token> lhsTokens = new ArrayList<>();
    NonTerminal nt;
    Action act;
    Token t;
    Lookahead la;

    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case _LOOKAHEAD:{
      /*
         * We give this priority over primary expressions which use LOOKAHEAD as the
         * name of its identifier.
         */
        t = jj_consume_token(_LOOKAHEAD);
      jj_consume_token(LPAREN);
      la = local_lookahead(p);
      jj_consume_token(RPAREN);

	// Now set the la_expansion field of la with a dummy
	// expansion (we use EOF).
	la.setLaExpansion(new REndOfFile());
	// Create a singleton choice with an empty action.
	var ch = new Choice();
	ch.setLocation(t);
	var seq = new Sequence();
	seq.setLocation(t);
	seq.getUnits().add(la);
	la.setParent(seq, 0);
	act = new Action();
	act.setLocation(t);
	seq.getUnits().add(act);
	act.setParent(seq, 1);
	ch.getChoices().add(seq);
	seq.setParent(ch, 0);
	if (la.getAmount() != 0) {
	  if (!la.getActionTokens().isEmpty())
	    JavaCCErrors.warning(t, "Encountered LOOKAHEAD(...) at a non-choice location.  Only semantic lookahead will be considered here.");
	  else
	    JavaCCErrors.warning(t, "Encountered LOOKAHEAD(...) at a non-choice location.  This will be ignored.");
	}
	c.set(ch);

      break;
      }
    case ECODE_DATA:
    case LBRACE:{

	act = new Action();
	t = getToken(1);
    act.setLocation(t);
    p.setIsAction();

      Statement(act.getActionTokens());

	if (inLocalLA != 0)
	  JavaCCErrors.warning(t, "Action within lookahead specification will be ignored.");
	c.set(act);
  
      break;
      }
    case LBRACKET:{
      t = jj_consume_token(LBRACKET);
      expansion_choices(c, p);
      jj_consume_token(RBRACKET);

	c.set(new ZeroOrOne(c.get()));
	c.get().setLocation(t);
  
      break;
      }
    default:
      jj_la1[25] = jj_gen;
      if (jj_2_4(2147483647)) {
        if (jj_2_2(2147483647)) {

	  var first = getToken(1);

          PrimaryExpression();

	  var last = getToken(0);

          jj_consume_token(ASSIGN);

	  t = first;
	  while (true) {
	    lhsTokens.add(t);
	    if (t == last) break;
	    t = t.next;
	  }

        } else {
          ;
        }
        if (jj_2_3(2147483647)) {

	  t = getToken(1);
	  nt = new NonTerminal();
	  nt.setLocation(t);
	  nt.setLhsTokens(lhsTokens);

          name = identifier();
          Arguments(nt.getArgumentTokens());

	  nt.setName(name);
	  c.set(nt);
	
        } else {
          switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
          case STRING_LITERAL:
          case LT:{
            regular_expression(c);

	  c.<RExpression>get().setLhsTokens(lhsTokens);
	  add_inline_regexpr(c.get());

            switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
            case DOT:{
              jj_consume_token(DOT);
              t = jj_consume_token(IDENTIFIER);
 c.<RExpression>get().setRhsToken(t); p.setNonTerminal(); 
              break;
              }
            default:
              jj_la1[21] = jj_gen;
              ;
            }
            break;
            }
          default:
            jj_la1[22] = jj_gen;
            jj_consume_token(-1);
            throw new ParseException();
          }
        }
      } else {
        switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
        case LPAREN:{
          t = jj_consume_token(LPAREN);
          expansion_choices(c, p);
          jj_consume_token(RPAREN);
          switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
          case HOOK:
          case PLUS:
          case STAR:{
            switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
            case PLUS:{
              jj_consume_token(PLUS);
 c.set(new OneOrMore(c.get())).setLocation(t); 
              break;
              }
            case STAR:{
              jj_consume_token(STAR);
 c.set(new ZeroOrMore(c.get())).setLocation(t); 
              break;
              }
            case HOOK:{
              jj_consume_token(HOOK);
 c.set(new ZeroOrOne(c.get())).setLocation(t); 
              break;
              }
            default:
              jj_la1[23] = jj_gen;
              jj_consume_token(-1);
              throw new ParseException();
            }
            break;
            }
          default:
            jj_la1[24] = jj_gen;
            ;
          }
          break;
          }
        default:
          jj_la1[26] = jj_gen;
          jj_consume_token(-1);
          throw new ParseException();
        }
      }
    }
}


  public final void regular_expression(Container c) throws ParseException {

    REndOfFile ef;
    String image;
    boolean private_rexp = false;
    var t = getToken(1);

    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case STRING_LITERAL:{
      image = StringLiteral();

	c.set(new RStringLiteral(image));
	c.get().setLocation(t);

      break;
      }
    default:
      jj_la1[29] = jj_gen;
      if (jj_2_5(3)) {

	image = "";

        jj_consume_token(LT);
        switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
        case HASH:
        case IDENTIFIER:{
          switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
          case HASH:{
            jj_consume_token(HASH);

	  private_rexp = true;

            break;
            }
          default:
            jj_la1[27] = jj_gen;
            ;
          }
          image = identifier();
          jj_consume_token(COLON);
          break;
          }
        default:
          jj_la1[28] = jj_gen;
          ;
        }
        complex_regular_expression_choices(c);
        jj_consume_token(GT);

	RExpression re;
	if (c.get() instanceof RJustName m) {
	  var seq = new RSequence();
	  seq.getUnits().add(m);
	  re = seq;
	} else {
	  re = c.get();
	}
	re.setLabel(image);
	re.setPrivateRegExp(private_rexp);
	re.setLocation(t);
	c.set(re);

      } else if (jj_2_6(2)) {
        jj_consume_token(LT);
        image = identifier();
        jj_consume_token(GT);

	c.set(new RJustName(image));
	c.get().setLocation(t);

      } else {
        switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
        case LT:{
          jj_consume_token(LT);
          jj_consume_token(_EOF);
          jj_consume_token(GT);

	ef = new REndOfFile();
	ef.setLocation(t);
  ef.setOrdinal(0);
	c.set(ef);

          break;
          }
        default:
          jj_la1[30] = jj_gen;
          jj_consume_token(-1);
          throw new ParseException();
        }
      }
    }
}


  public final void complex_regular_expression_choices(Container c1) throws ParseException {

    boolean morethanone = false;
    RChoice ch = null; // unnecessary initialization to make Java compiler happy!
    var c2 = new Container();

    complex_regular_expression(c1);
    label_8:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case BIT_OR:{
        ;
        break;
        }
      default:
        jj_la1[31] = jj_gen;
        break label_8;
      }
      jj_consume_token(BIT_OR);
      complex_regular_expression(c2);

	  if (morethanone) {
	    ch.getChoices().add(c2.get());
	  } else {
	    morethanone = true;
	    ch = new RChoice();
	    ch.setLocation(c1.get());
	    ch.getChoices().add(c1.get());
	    ch.getChoices().add(c2.get());
	  }

    }

	if (morethanone)
	  c1.set(ch);

}


  public final void complex_regular_expression(Container c1) throws ParseException {

    int count = 0;
    RSequence seq = null; // unnecessary initialization to make Java compiler happy!
    var c2 = new Container();

    label_9:
    while (true) {
      complex_regular_expression_unit(c2);

	  count++;
	  if (count == 1)
	    c1.set(c2.get()); // if count does not go beyond 1, we are done.
	  else if (count == 2) { // more than 1, so create a sequence.
	    seq = new RSequence();
	    seq.setLocation(c1.get());
	    seq.getUnits().add(c1.get());
	    seq.getUnits().add(c2.get());
	  } else
	    seq.getUnits().add(c2.get());

      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case STRING_LITERAL:
      case LPAREN:
      case LBRACKET:
      case LT:
      case TILDE:{
        ;
        break;
        }
      default:
        jj_la1[32] = jj_gen;
        break label_9;
      }
    }

	if (count > 1)
	  c1.set(seq);

}


  public final void complex_regular_expression_unit(Container c) throws ParseException {

    String image;
    var t = getToken(1);
    int r1 = 0, r2 = -1;
    boolean hasMax = false;

    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case STRING_LITERAL:{
      image = StringLiteral();

	c.set(new RStringLiteral(image));
	c.get().setLocation(t);

      break;
      }
    case LT:{
      jj_consume_token(LT);
      image = identifier();
      jj_consume_token(GT);

	c.set(new RJustName(image));
	c.get().setLocation(t);
  
      break;
      }
    case LBRACKET:
    case TILDE:{
      character_list(c);
      break;
      }
    case LPAREN:{
      jj_consume_token(LPAREN);
      complex_regular_expression_choices(c);
      jj_consume_token(RPAREN);
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case LBRACE:
      case HOOK:
      case PLUS:
      case STAR:{
        switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
        case PLUS:{
          jj_consume_token(PLUS);

	  c.set(new ROneOrMore(c.get()));
	  c.get().setLocation(t);

          break;
          }
        case STAR:{
          jj_consume_token(STAR);

	  c.set(new RZeroOrMore(c.get()));
	  c.get().setLocation(t);

          break;
          }
        case HOOK:{
          jj_consume_token(HOOK);

	  c.set(new RZeroOrOne(c.get()));
	  c.get().setLocation(t);

          break;
          }
        case LBRACE:{
          jj_consume_token(LBRACE);
          r1 = IntegerLiteral();
          switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
          case COMMA:{
            jj_consume_token(COMMA);
 hasMax = true; 
            switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
            case INTEGER_LITERAL:{
              r2 = IntegerLiteral();
              break;
              }
            default:
              jj_la1[33] = jj_gen;
              ;
            }
            break;
            }
          default:
            jj_la1[34] = jj_gen;
            ;
          }
          jj_consume_token(RBRACE);

	  c.set(new RRepetitionRange(c.get(), r1, r2, hasMax));
	  c.get().setLocation(t);

          break;
          }
        default:
          jj_la1[35] = jj_gen;
          jj_consume_token(-1);
          throw new ParseException();
        }
        break;
        }
      default:
        jj_la1[36] = jj_gen;
        ;
      }
      break;
      }
    default:
      jj_la1[37] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
}


  public final void character_list(Container c1) throws ParseException {

    var p = new RCharacterList();
    var t = getToken(1);
    p.setLocation(t);
    var c2 = new Container();

    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case TILDE:{
      jj_consume_token(TILDE);
 p.setNegatedList(); 
      break;
      }
    default:
      jj_la1[38] = jj_gen;
      ;
    }
    jj_consume_token(LBRACKET);
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case STRING_LITERAL:{
      character_descriptor(c2);

	p.getDescriptors().add(c2.get());

      label_10:
      while (true) {
        switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
        case COMMA:{
          ;
          break;
          }
        default:
          jj_la1[39] = jj_gen;
          break label_10;
        }
        jj_consume_token(COMMA);
        character_descriptor(c2);

	p.getDescriptors().add(c2.get());

      }
      break;
      }
    default:
      jj_la1[40] = jj_gen;
      ;
    }
    jj_consume_token(RBRACKET);

	c1.set(p);

}


  public final void character_descriptor(Container c) throws ParseException {

    char c1, c2 = ' '; // unnecessary initialization to make Java compiler happy!
    boolean isrange = false;
    String imageL, imageR;
    var t = getToken(1);

    imageL = StringLiteral();

	c1 = character_descriptor_assign(getToken(0), imageL);

    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case MINUS:{
      jj_consume_token(MINUS);
      imageR = StringLiteral();

	isrange = true;
	c2 = character_descriptor_assign(getToken(0), imageR, imageL);

      break;
      }
    default:
      jj_la1[41] = jj_gen;
      ;
    }

	c.set(isrange ? new CharacterRange(c1, c2) : new SingleCharacter(c1));
	c.get().setLocation(t);

}


  public final                     String identifier() throws ParseException {
    jj_consume_token(IDENTIFIER);

	return getToken(0).image;

}


/**********************************************
 * THE JJTREE PRODUCTIONS START HERE       *
 **********************************************/
  public final void node_descriptor(Expansion exp, BNFProduction p) throws ParseException {

    ParserDescriptor nd = new ParserDescriptor();

    jj_consume_token(HASH);
    TypeParameter();
 nd.setName(getToken(0).image); 
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case LPAREN:{
      jj_consume_token(LPAREN);
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case GT:{
        jj_consume_token(GT);
 nd.setGreaterThan(); 
        break;
        }
      default:
        jj_la1[42] = jj_gen;
        ;
      }
      value();
 nd.setExpressionText(getToken(0).image); 
      jj_consume_token(RPAREN);
      break;
      }
    default:
      jj_la1[43] = jj_gen;
      ;
    }

  exp.setNodeScope(NodeScope.create(p, nd));

}


  public final void value() throws ParseException {
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case INTEGER_LITERAL:{
      jj_consume_token(INTEGER_LITERAL);
      break;
      }
    case FALSE:{
      jj_consume_token(FALSE);
      break;
      }
    case TRUE:{
      jj_consume_token(TRUE);
      break;
      }
    default:
      jj_la1[44] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
}


/**********************************************
 * THE JAVA GRAMMAR SPECIFICATION STARTS HERE *
 **********************************************/

/*
 * The following production defines Java identifiers - it
 * includes the reserved words of JavaCC also.
 */
  public final 
                       Token TypeParameter() throws ParseException {
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case IDENTIFIER:{
      jj_consume_token(IDENTIFIER);
      break;
      }
    case _LOOKAHEAD:{
      jj_consume_token(_LOOKAHEAD);
      break;
      }
    case _IGNORE_CASE:{
      jj_consume_token(_IGNORE_CASE);
      break;
      }
    case _PARSER:{
      jj_consume_token(_PARSER);
      break;
      }
    case _TOKEN:{
      jj_consume_token(_TOKEN);
      break;
      }
    case _SPECIAL_TOKEN:{
      jj_consume_token(_SPECIAL_TOKEN);
      break;
      }
    case _MORE:{
      jj_consume_token(_MORE);
      break;
      }
    case _SKIP:{
      jj_consume_token(_SKIP);
      break;
      }
    case _EOF:{
      jj_consume_token(_EOF);
      break;
      }
    default:
      jj_la1[45] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }

  var retval = getToken(0);
  retval.kind = IDENTIFIER;
  return retval;

}


/*
 * Program structuring syntax follows.
 */
  public final void FormalParameters(List<Token> tokens) throws ParseException {
/*
 * Parsing this fills "tokens" with all tokens of the formal
 * parameters excluding the parentheses at each end.
 */

    Token first, last;

    jj_consume_token(LPAREN);

	first = getToken(1);

    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case BOOLEAN:
    case INT:
    case CHAR:
    case IDENTIFIER:{
      FormalParameter();
      label_11:
      while (true) {
        switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
        case COMMA:{
          ;
          break;
          }
        default:
          jj_la1[46] = jj_gen;
          break label_11;
        }
        jj_consume_token(COMMA);
        FormalParameter();
      }
      break;
      }
    default:
      jj_la1[47] = jj_gen;
      ;
    }

	last = getToken(0);

    jj_consume_token(RPAREN);

	if (last.next != first) { // i.e., this is not an empty sequence
	  Token t = first;
	  while (true) {
	    tokens.add(t);
	    if (t == last) break;
	    t = t.next;
	  }
	}

}


  public final void FormalParameter() throws ParseException {
    Type();
    TypeParameter();
}


/*
 * Type, name and expression syntax follows.
 */
  public final void Type() throws ParseException {
    if (jj_2_7(2)) {
      ClassOrInterfaceType();
    } else {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case BOOLEAN:
      case INT:
      case CHAR:{
        PrimitiveType();
        break;
        }
      default:
        jj_la1[48] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
    }
}


  public final void ClassOrInterfaceType() throws ParseException {
    jj_consume_token(IDENTIFIER);
    if (jj_2_8(2)) {
      TypeArguments();
    } else {
      ;
    }
}


  public final void TypeArguments(List<Token> tokens) throws ParseException {
/*
 * Parsing this fills "tokens" with all tokens of the arguments
 * excluding the parentheses at each end.
 */

    Token first, last;

    jj_consume_token(LT);
    first = getToken(0); 
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case IDENTIFIER:{
      ClassOrInterfaceType();
      break;
      }
    default:
      jj_la1[49] = jj_gen;
      ;
    }
    jj_consume_token(GT);

  last = getToken(0);
  if (last.next != first) { // i.e., this is not an empty sequence
    var t = first;
    while (true) {
      tokens.add(t);
      if (t == last)
        break;
	    t = t.next;
	  }
	}

}


  public final void PrimitiveType() throws ParseException {
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case BOOLEAN:{
      jj_consume_token(BOOLEAN);
      break;
      }
    case CHAR:{
      jj_consume_token(CHAR);
      break;
      }
    case INT:{
      jj_consume_token(INT);
      break;
      }
    default:
      jj_la1[50] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
}


  public final void Name(List<Token> tokens) throws ParseException {
/*
 * A lookahead of 2 is required below since "Name" can be followed
 * by a ".*" when used in the context of an "ImportDeclaration".
 */

  var first = getToken(1);

    TypeParameter();
    label_12:
    while (true) {
      if (jj_2_9(2)) {
        ;
      } else {
        break label_12;
      }
      jj_consume_token(DOT);
      TypeParameter();
    }

  var last = getToken(0);
  var t = first;
  while (true) {
    tokens.add(t);
    if (t == last)
      break;
	  t = t.next;
  }

}


/*
 * Expression syntax follows.
 * This expansion has been written this way instead of:
 *   Assignment() | ConditionalExpression()
 * for performance reasons.
 * However, it is a weakening of the grammar for it allows the LHS of
 * assignments to be any conditional expression whereas it can only be
 * a primary expression.  Consider adding a semantic predicate to work
 * around this.
 */
  public final void Expression(List<Token> tokens) throws ParseException {

  var first = getToken(1);

    PrimaryExpression();

	var last = getToken(0);
	var t = first;
	while (true) {
	  tokens.add(t);
	  if (t == last) break;
	  t = t.next;
	}

}


  public final void PrimaryExpression() throws ParseException {
    PrimaryPrefix();
    label_13:
    while (true) {
      if (jj_2_10(2)) {
        ;
      } else {
        break label_13;
      }
      PrimarySuffix();
    }
}


  public final void PrimaryPrefix() throws ParseException {
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case NULL:
    case TRUE:
    case FALSE:
    case INTEGER_LITERAL:
    case FLOATING_POINT_LITERAL:
    case CHARACTER_LITERAL:
    case STRING_LITERAL:{
      Literal();
      break;
      }
    case LPAREN:{
      jj_consume_token(LPAREN);
      Expression();
      jj_consume_token(RPAREN);
      break;
      }
    case _LOOKAHEAD:
    case _IGNORE_CASE:
    case _PARSER:
    case _TOKEN:
    case _SPECIAL_TOKEN:
    case _MORE:
    case _SKIP:
    case _EOF:
    case IDENTIFIER:{
      Name();
      break;
      }
    default:
      jj_la1[51] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
}


  public final void PrimarySuffix() throws ParseException {
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case LBRACKET:{
      jj_consume_token(LBRACKET);
      Expression();
      jj_consume_token(RBRACKET);
      break;
      }
    case LPAREN:{
      Arguments();
      break;
      }
    default:
      jj_la1[52] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
}


  public final void Literal() throws ParseException {
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case NULL:{
      jj_consume_token(NULL);
      break;
      }
    case INTEGER_LITERAL:{
      jj_consume_token(INTEGER_LITERAL);
      break;
      }
    case FLOATING_POINT_LITERAL:{
      jj_consume_token(FLOATING_POINT_LITERAL);
      break;
      }
    case CHARACTER_LITERAL:{
      jj_consume_token(CHARACTER_LITERAL);
      break;
      }
    case STRING_LITERAL:{
      jj_consume_token(STRING_LITERAL);
      break;
      }
    case TRUE:
    case FALSE:{
      BooleanLiteral();
      break;
      }
    default:
      jj_la1[53] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
}


  public final                         int IntegerLiteral() throws ParseException {
    jj_consume_token(INTEGER_LITERAL);
 return Integer.parseInt(token.image); 
}


  public final void BooleanLiteral() throws ParseException {
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case TRUE:{
      jj_consume_token(TRUE);
      break;
      }
    case FALSE:{
      jj_consume_token(FALSE);
      break;
      }
    default:
      jj_la1[54] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
}


  public final                        String StringLiteral() throws ParseException {
    jj_consume_token(STRING_LITERAL);
 return remove_escapes_and_quotes(this.token, this.token.image); 
}


/*
 * Parsing this fills "tokens" with all tokens of the arguments
 * excluding the parentheses at each end.
 */
  public final void Arguments(List<Token> tokens) throws ParseException {

    Token first, last;

    jj_consume_token(LPAREN);

    first = getToken(1);

    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case _LOOKAHEAD:
    case _IGNORE_CASE:
    case _PARSER:
    case _TOKEN:
    case _SPECIAL_TOKEN:
    case _MORE:
    case _SKIP:
    case _EOF:
    case NULL:
    case TRUE:
    case FALSE:
    case INTEGER_LITERAL:
    case FLOATING_POINT_LITERAL:
    case CHARACTER_LITERAL:
    case STRING_LITERAL:
    case LPAREN:
    case IDENTIFIER:{
      Expression();
      label_14:
      while (true) {
        switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
        case COMMA:{
          ;
          break;
          }
        default:
          jj_la1[55] = jj_gen;
          break label_14;
        }
        jj_consume_token(COMMA);
        Expression();
      }
      break;
      }
    default:
      jj_la1[56] = jj_gen;
      ;
    }

    last = getToken(0);

    jj_consume_token(RPAREN);

    if (last.next != first) { // i.e., this is not an empty sequence
      Token t = first;
      while (true) {
        tokens.add(t);
        if (t == last) break;
	    t = t.next;
      }
    }

}


/*
 * Statement syntax follows.
 * Parsing this fills "tokens" with all tokens of the block
 * excluding the braces at each end.
 */
  public final void Statement(List<Token> tokens) throws ParseException {

    Token first, last;

    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case ECODE_DATA:{
      jj_consume_token(ECODE_DATA);
 tokens.add(getToken(0)); 
      jj_consume_token(ECODE_END);
      break;
      }
    case LBRACE:{
      jj_consume_token(LBRACE);
 first = getToken(1); 
      label_15:
      while (true) {
        switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
        case ECODE_DATA:
        case LBRACE:{
          ;
          break;
          }
        default:
          jj_la1[57] = jj_gen;
          break label_15;
        }
        Statement();
      }
 last = getToken(0); 
      jj_consume_token(RBRACE);

    if (last.next != first) { // i.e., this is not an empty sequence
      var t = first;
      while (true) {
        tokens.add(t);
        if (t == last)
          break;
	    t = t.next;
      }
	}

      break;
      }
    default:
      jj_la1[58] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
}


  private boolean jj_2_1(int xla) {
    jj_la = xla;
    jj_lastpos = jj_scanpos = token;
    try {
      return (!jj_3_1());
    } catch (LookaheadSuccess ls) {
      return true;
    } finally {
      jj_save(0, xla);
    }
  }


  private boolean jj_2_2(int xla) {
    jj_la = xla;
    jj_lastpos = jj_scanpos = token;
    try {
      return (!jj_3_2());
    } catch (LookaheadSuccess ls) {
      return true;
    } finally {
      jj_save(1, xla);
    }
  }


  private boolean jj_2_3(int xla) {
    jj_la = xla;
    jj_lastpos = jj_scanpos = token;
    try {
      return (!jj_3_3());
    } catch (LookaheadSuccess ls) {
      return true;
    } finally {
      jj_save(2, xla);
    }
  }


  private boolean jj_2_4(int xla) {
    jj_la = xla;
    jj_lastpos = jj_scanpos = token;
    try {
      return (!jj_3_4());
    } catch (LookaheadSuccess ls) {
      return true;
    } finally {
      jj_save(3, xla);
    }
  }


  private boolean jj_2_5(int xla) {
    jj_la = xla;
    jj_lastpos = jj_scanpos = token;
    try {
      return (!jj_3_5());
    } catch (LookaheadSuccess ls) {
      return true;
    } finally {
      jj_save(4, xla);
    }
  }


  private boolean jj_2_6(int xla) {
    jj_la = xla;
    jj_lastpos = jj_scanpos = token;
    try {
      return (!jj_3_6());
    } catch (LookaheadSuccess ls) {
      return true;
    } finally {
      jj_save(5, xla);
    }
  }


  private boolean jj_2_7(int xla) {
    jj_la = xla;
    jj_lastpos = jj_scanpos = token;
    try {
      return (!jj_3_7());
    } catch (LookaheadSuccess ls) {
      return true;
    } finally {
      jj_save(6, xla);
    }
  }


  private boolean jj_2_8(int xla) {
    jj_la = xla;
    jj_lastpos = jj_scanpos = token;
    try {
      return (!jj_3_8());
    } catch (LookaheadSuccess ls) {
      return true;
    } finally {
      jj_save(7, xla);
    }
  }


  private boolean jj_2_9(int xla) {
    jj_la = xla;
    jj_lastpos = jj_scanpos = token;
    try {
      return (!jj_3_9());
    } catch (LookaheadSuccess ls) {
      return true;
    } finally {
      jj_save(8, xla);
    }
  }


  private boolean jj_2_10(int xla) {
    jj_la = xla;
    jj_lastpos = jj_scanpos = token;
    try {
      return (!jj_3_10());
    } catch (LookaheadSuccess ls) {
      return true;
    } finally {
      jj_save(9, xla);
    }
  }


  private boolean jj_3R_regular_expression_6() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_regular_expression_14()) jj_scanpos = xsp;
    if (jj_3R_identifier_2())
      return true;
    if (jj_scan_token(ParserConstants.COLON))
      return true;
    return false;
  }


  private boolean jj_3R_PrimarySuffix_11() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_PrimarySuffix_18()) {
      jj_scanpos = xsp;
    if (jj_3R_PrimarySuffix_19())
      return true;
    }
    return false;
  }


  private boolean jj_3R_PrimarySuffix_18() {
    if (jj_scan_token(ParserConstants.LBRACKET))
      return true;
    if (jj_3R_Expression_24())
      return true;
    if (jj_scan_token(ParserConstants.RBRACKET))
      return true;
    return false;
  }


  private boolean jj_3_7() {
    if (jj_3R_ClassOrInterfaceType_8())
      return true;
    return false;
  }


  private boolean jj_3R_PrimaryPrefix_22() {
    if (jj_3R_Name_27())
      return true;
    return false;
  }


  private boolean jj_3R_PrimaryPrefix_21() {
    if (jj_scan_token(ParserConstants.LPAREN))
      return true;
    if (jj_3R_Expression_24())
      return true;
    if (jj_scan_token(ParserConstants.RPAREN))
      return true;
    return false;
  }


  private boolean jj_3R_complex_regular_expression_unit_28() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_complex_regular_expression_unit_31()) {
      jj_scanpos = xsp;
    if (jj_3R_complex_regular_expression_unit_32()) {
      jj_scanpos = xsp;
    if (jj_3R_complex_regular_expression_unit_33()) {
      jj_scanpos = xsp;
    if (jj_3R_complex_regular_expression_unit_34())
      return true;
    }
    }
    }
    return false;
  }


  private boolean jj_3R_PrimaryPrefix_12() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_PrimaryPrefix_20()) {
      jj_scanpos = xsp;
    if (jj_3R_PrimaryPrefix_21()) {
      jj_scanpos = xsp;
    if (jj_3R_PrimaryPrefix_22())
      return true;
    }
    }
    return false;
  }


  private boolean jj_3R_PrimaryPrefix_20() {
    if (jj_3R_Literal_26())
      return true;
    return false;
  }


  private boolean jj_3R_identifier_2() {
    if (jj_scan_token(ParserConstants.IDENTIFIER))
      return true;
    return false;
  }


  private boolean jj_3_5() {
    if (jj_scan_token(ParserConstants.LT))
      return true;
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_regular_expression_6()) jj_scanpos = xsp;
    if (jj_3R_complex_regular_expression_choices_7())
      return true;
    if (jj_scan_token(ParserConstants.GT))
      return true;
    return false;
  }


  private boolean jj_3R_PrimaryExpression_1() {
    if (jj_3R_PrimaryPrefix_12())
      return true;
    Token xsp;
    while (true) {
      xsp = jj_scanpos;
      if (jj_3_10()) { jj_scanpos = xsp; break; }
    }
    return false;
  }


  private boolean jj_3R_complex_regular_expression_23() {
    if (jj_3R_complex_regular_expression_unit_28())
      return true;
    return false;
  }


  private boolean jj_3_1() {
    if (jj_scan_token(ParserConstants.LT))
      return true;
    if (jj_scan_token(ParserConstants.STAR))
      return true;
    return false;
  }


  private boolean jj_3R_Expression_24() {
    if (jj_3R_PrimaryExpression_1())
      return true;
    return false;
  }


  private boolean jj_3R_character_descriptor_40() {
    if (jj_3R_StringLiteral_13())
      return true;
    return false;
  }


  private boolean jj_3R_character_list_39() {
    if (jj_3R_character_descriptor_40())
      return true;
    return false;
  }


  private boolean jj_3R_complex_regular_expression_15() {
    Token xsp;
    if (jj_3R_complex_regular_expression_23()) return true;
    while (true) {
      xsp = jj_scanpos;
      if (jj_3R_complex_regular_expression_23()) { jj_scanpos = xsp; break; }
    }
    return false;
  }


  private boolean jj_3_3() {
    if (jj_3R_identifier_2())
      return true;
    if (jj_scan_token(ParserConstants.LPAREN))
      return true;
    return false;
  }


  private boolean jj_3R_TypeArguments_17() {
    if (jj_3R_ClassOrInterfaceType_8())
      return true;
    return false;
  }


  private boolean jj_3R_character_list_38() {
    if (jj_scan_token(ParserConstants.TILDE))
      return true;
    return false;
  }


  private boolean jj_3R_StringLiteral_13() {
    if (jj_scan_token(ParserConstants.STRING_LITERAL))
      return true;
    return false;
  }


  private boolean jj_3R_Arguments_37() {
    if (jj_scan_token(ParserConstants.COMMA))
      return true;
    if (jj_3R_Expression_24())
      return true;
    return false;
  }


  private boolean jj_3R_complex_regular_expression_choices_16() {
    if (jj_scan_token(ParserConstants.BIT_OR))
      return true;
    return false;
  }


  private boolean jj_3_9() {
    if (jj_scan_token(ParserConstants.DOT))
      return true;
    if (jj_3R_TypeParameter_10())
      return true;
    return false;
  }





  private boolean jj_3R_character_list_36() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_character_list_38()) jj_scanpos = xsp;
    if (jj_scan_token(ParserConstants.LBRACKET))
      return true;
    xsp = jj_scanpos;
    if (jj_3R_character_list_39()) jj_scanpos = xsp;
    if (jj_scan_token(ParserConstants.RBRACKET))
      return true;
    return false;
  }




  private boolean jj_3R_BooleanLiteral_35() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_scan_token(TRUE)) {
      jj_scanpos = xsp;
    if (jj_scan_token(FALSE))
      return true;
    }
    return false;
  }



  private boolean jj_3R_Name_27() {
    if (jj_3R_TypeParameter_10())
      return true;
    Token xsp;
    while (true) {
      xsp = jj_scanpos;
      if (jj_3_9()) { jj_scanpos = xsp; break; }
    }
    return false;
  }


  private boolean jj_3_2() {
    if (jj_3R_PrimaryExpression_1())
      return true;
    if (jj_scan_token(ParserConstants.ASSIGN))
      return true;
    return false;
  }





  private boolean jj_3R_complex_regular_expression_choices_7() {
    if (jj_3R_complex_regular_expression_15())
      return true;
    Token xsp;
    while (true) {
      xsp = jj_scanpos;
      if (jj_3R_complex_regular_expression_choices_16()) { jj_scanpos = xsp; break; }
    }
    return false;
  }


  private boolean jj_3R_Arguments_29() {
    if (jj_3R_Expression_24())
      return true;
    Token xsp;
    while (true) {
      xsp = jj_scanpos;
      if (jj_3R_Arguments_37()) { jj_scanpos = xsp; break; }
    }
    return false;
  }


  private boolean jj_3R_TypeParameter_10() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_scan_token(IDENTIFIER)) {
      jj_scanpos = xsp;
    if (jj_scan_token(_LOOKAHEAD)) {
      jj_scanpos = xsp;
    if (jj_scan_token(_IGNORE_CASE)) {
      jj_scanpos = xsp;
    if (jj_scan_token(_PARSER)) {
      jj_scanpos = xsp;
    if (jj_scan_token(_TOKEN)) {
      jj_scanpos = xsp;
    if (jj_scan_token(_SPECIAL_TOKEN)) {
      jj_scanpos = xsp;
    if (jj_scan_token(_MORE)) {
      jj_scanpos = xsp;
    if (jj_scan_token(_SKIP)) {
      jj_scanpos = xsp;
    if (jj_scan_token(_EOF))
      return true;
    }
    }
    }
    }
    }
    }
    }
    }
    return false;
  }


  private boolean jj_3R_null_5() {
    if (jj_3R_PrimaryExpression_1())
      return true;
    if (jj_scan_token(ParserConstants.ASSIGN))
      return true;
    return false;
  }


  private boolean jj_3R_null_4() {
    if (jj_3R_StringLiteral_13())
      return true;
    return false;
  }


  private boolean jj_3R_null_3() {
    if (jj_3R_identifier_2())
      return true;
    return false;
  }


  private boolean jj_3_4() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_null_3()) {
      jj_scanpos = xsp;
    if (jj_3R_null_4()) {
      jj_scanpos = xsp;
    if (jj_scan_token(LT)) {
      jj_scanpos = xsp;
    if (jj_3R_null_5())
      return true;
    }
    }
    }
    return false;
  }


  private boolean jj_3R_Arguments_25() {
    if (jj_scan_token(ParserConstants.LPAREN))
      return true;
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_Arguments_29()) jj_scanpos = xsp;
    if (jj_scan_token(ParserConstants.RPAREN))
      return true;
    return false;
  }


  private boolean jj_3_6() {
    if (jj_scan_token(ParserConstants.LT))
      return true;
    if (jj_3R_identifier_2())
      return true;
    return false;
  }


  private boolean jj_3_8() {
    if (jj_3R_TypeArguments_9())
      return true;
    return false;
  }


  private boolean jj_3R_complex_regular_expression_unit_34() {
    if (jj_scan_token(ParserConstants.LPAREN))
      return true;
    if (jj_3R_complex_regular_expression_choices_7())
      return true;
    return false;
  }


  private boolean jj_3R_complex_regular_expression_unit_33() {
    if (jj_3R_character_list_36())
      return true;
    return false;
  }


  private boolean jj_3R_Literal_30() {
    if (jj_3R_BooleanLiteral_35())
      return true;
    return false;
  }


  private boolean jj_3R_TypeArguments_9() {
    if (jj_scan_token(ParserConstants.LT))
      return true;
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_TypeArguments_17()) jj_scanpos = xsp;
    if (jj_scan_token(ParserConstants.GT))
      return true;
    return false;
  }


  private boolean jj_3R_complex_regular_expression_unit_32() {
    if (jj_scan_token(ParserConstants.LT))
      return true;
    if (jj_3R_identifier_2())
      return true;
    return false;
  }


  private boolean jj_3_10() {
    if (jj_3R_PrimarySuffix_11())
      return true;
    return false;
  }


  private boolean jj_3R_Literal_26() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_scan_token(NULL)) {
      jj_scanpos = xsp;
    if (jj_scan_token(INTEGER_LITERAL)) {
      jj_scanpos = xsp;
    if (jj_scan_token(FLOATING_POINT_LITERAL)) {
      jj_scanpos = xsp;
    if (jj_scan_token(CHARACTER_LITERAL)) {
      jj_scanpos = xsp;
    if (jj_scan_token(STRING_LITERAL)) {
      jj_scanpos = xsp;
    if (jj_3R_Literal_30())
      return true;
    }
    }
    }
    }
    }
    return false;
  }


  private boolean jj_3R_complex_regular_expression_unit_31() {
    if (jj_3R_StringLiteral_13())
      return true;
    return false;
  }


  private boolean jj_3R_ClassOrInterfaceType_8() {
    if (jj_scan_token(ParserConstants.IDENTIFIER))
      return true;
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3_8()) jj_scanpos = xsp;
    return false;
  }


  private boolean jj_3R_regular_expression_14() {
    if (jj_scan_token(ParserConstants.HASH))
      return true;
    return false;
  }


  private boolean jj_3R_PrimarySuffix_19() {
    if (jj_3R_Arguments_25())
      return true;
    return false;
  }



  /** Generated Token Manager. */
  public Lexer               token_source;
  /** Current token. */
  public Token token;
  /** Next token. */
  public Token               jj_nt;
  private int                jj_ntk;
  private Token              jj_scanpos, jj_lastpos;
  private int                jj_la;
  private int                jj_gen;
  private final int[]        jj_la1    = new int[59];
  private static final int[] jj_la1_0  = { 0x0, 0x100, 0xf0, 0x38000000, 0x0, 0x0, 0x200000, 0x200000, 0x0, 0x0, 0x0, 0x0, 0x0, 0xf0, 0x200000, 0x0, 0x0, 0x2, 0x0, 0x20000000, 0x3c0002fe, 0x0, 0x0, 0x0, 0x0, 0x200002, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x20000000, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x38000000, 0x2fe, 0x0, 0x3800000, 0x3800000, 0x0, 0x3800000, 0x3c0002fe, 0x0, 0x3c000000, 0x18000000, 0x0, 0x3c0002fe, 0x200000, 0x200000};
  private static final int[] jj_la1_1  = { 0x4000, 0x0, 0x100000, 0x80, 0x2000000, 0x1000000, 0x0, 0x0, 0x4000, 0x100000, 0x100000, 0x1000, 0x20000000, 0x0, 0x400, 0x2000000, 0x20000000, 0x0, 0x1000000, 0x0, 0x400001c2, 0x20000, 0x100080, 0x14800000, 0x14800000, 0x1400, 0x100, 0x1000000, 0x41000000, 0x80, 0x100000, 0x20000000, 0x501180, 0x0, 0x4000, 0x14800400, 0x14800400, 0x501180, 0x400000, 0x4000, 0x80, 0x8000000, 0x80000, 0x100, 0x0, 0x40000000, 0x4000, 0x40000000, 0x0, 0x40000000, 0x0, 0x400001c2, 0x1100, 0xc2, 0x0, 0x4000, 0x400001c2, 0x400, 0x400};
  private static final int[] jj_la1_2  = { 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0};
  private final JJCalls[]    jj_2_rtns = new JJCalls[10];
  private boolean            jj_rescan = false;
  private int                jj_gc     = 0;

  /** Constructor. */
  public Parser(Provider stream) {
    this(new Lexer(new JavaCharStream(stream)));
  }

  /** Constructor. */
  public Parser(String dsl) throws ParseException, TokenException {
    this(new StringProvider(dsl));
  }

  /** Constructor with generated Token Manager. */
  public Parser(Lexer tm) {
    token_source = tm;
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 59; i++)
      jj_la1[i] = -1;
    for (int i = 0; i < jj_2_rtns.length; i++)
      jj_2_rtns[i] = new JJCalls();
  }

  /** Reinitialise. */
  public void ReInit(Lexer tm) {
    token_source = tm;
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 59; i++)
      jj_la1[i] = -1;
    for (int i = 0; i < jj_2_rtns.length; i++)
      jj_2_rtns[i] = new JJCalls();
  }

  private Token jj_consume_token(int kind) throws ParseException {
    Token oldToken;
    if ((oldToken = token).next != null)
      token = token.next;
    else
      token = token.next = token_source.getNextToken();
    jj_ntk = -1;
    if (token.kind == kind) {
      jj_gen++;
      if (++jj_gc > 100) {
        jj_gc = 0;
        for (int i = 0; i < jj_2_rtns.length; i++) {
          JJCalls c = jj_2_rtns[i];
          while (c != null) {
            if (c.gen < jj_gen)
              c.first = null;
            c = c.next;
          }
        }
      }
      return this.token;
    }
    this.token = oldToken;
    this.jj_kind = kind;
    throw generateParseException();
  }

  @SuppressWarnings("serial")
  static private final class LookaheadSuccess extends java.lang.RuntimeException {
    @Override
    public Throwable fillInStackTrace() {
      return this;
    }
  }
  static private final LookaheadSuccess jj_ls = new LookaheadSuccess();
  private boolean jj_scan_token(int kind) {
    if (jj_scanpos == jj_lastpos) {
      jj_la--;
      if (jj_scanpos.next == null) {
        jj_lastpos = jj_scanpos = jj_scanpos.next = token_source.getNextToken();
      } else {
        jj_lastpos = jj_scanpos = jj_scanpos.next;
      }
    } else {
      jj_scanpos = jj_scanpos.next;
    }
    if (jj_rescan) {
      int i = 0;
      Token tok = token;
      while (tok != null && tok != jj_scanpos) {
        i++;
        tok = tok.next;
      }
      if (tok != null)
        jj_add_error_token(kind, i);
    }
    if (jj_scanpos.kind != kind)
      return true;
    if (jj_la == 0 && jj_scanpos == jj_lastpos)
      throw Parser.jj_ls;
    return false;
  }


  /** Get the next Token. */
  final public Token getNextToken() {
    if (token.next != null)
      token = token.next;
    else
      token = token.next = token_source.getNextToken();
      jj_ntk = -1;
    jj_gen++;
    return this.token;
  }

  /** Get the specific Token. */
  final public Token getToken(int index) {
    Token t = this.token;
    for (int i = 0; i < index; i++) {
      if (t.next != null)
        t = t.next;
      else
        t = t.next = token_source.getNextToken();
    }
    return t;
  }

  private int jj_ntk_f() {
    if ((jj_nt=token.next) == null)
      return (jj_ntk = (token.next=token_source.getNextToken()).kind);
    else
      return (jj_ntk = jj_nt.kind);
  }

  private final java.util.List<int[]> jj_expentries = new java.util.ArrayList<>();
  private int[]                       jj_expentry;
  private int                         jj_kind       = -1;
  private final int[]                 jj_lasttokens = new int[100];
  private int                         jj_endpos;

  private void jj_add_error_token(int kind, int pos) {
    if (pos >= 100) {
      return;
    }

    if (pos == (this.jj_endpos + 1)) {
      this.jj_lasttokens[this.jj_endpos++] = kind;
    } else if (this.jj_endpos != 0) {
      this.jj_expentry = new int[this.jj_endpos];

      for (int i = 0; i < this.jj_endpos; i++) {
        this.jj_expentry[i] = this.jj_lasttokens[i];
      }

      for (int[] oldentry : this.jj_expentries) {
        if (oldentry.length == this.jj_expentry.length) {
          boolean isMatched = true;

          for (int i = 0; i < this.jj_expentry.length; i++) {
            if (oldentry[i] != this.jj_expentry[i]) {
              isMatched = false;
              break;
            }

          }
          if (isMatched) {
            this.jj_expentries.add(this.jj_expentry);
            break;
          }
        }
      }

      if (pos != 0) {
        this.jj_lasttokens[(this.jj_endpos = pos) - 1] = kind;
      }
    }
  }

    /**
     * Generate ParseException.
     */
    public ParseException generateParseException() {
        this.jj_expentries.clear();
        boolean[] la1tokens = new boolean[65];
        if (this.jj_kind >= 0) {
            la1tokens[this.jj_kind] = true;
            this.jj_kind = -1;
        }
        for (int i = 0; i < 59; i++) {
            if (this.jj_la1[i] == this.jj_gen) {
                for (int j = 0; j < 32; j++) {
                    if ((Parser.jj_la1_0[i] & (1 << j)) != 0) {
                        la1tokens[j] = true;
                    }
                    if ((Parser.jj_la1_1[i] & (1 << j)) != 0) {
                        la1tokens[32 + j] = true;
                    }
                    if ((Parser.jj_la1_2[i] & (1 << j)) != 0) {
                        la1tokens[64 + j] = true;
                    }
                }
            }
        }
        for (int i = 0; i < 65; i++) {
            if (la1tokens[i]) {
                this.jj_expentry = new int[1];
                this.jj_expentry[0] = i;
                this.jj_expentries.add(this.jj_expentry);
            }
        }
        this.jj_endpos = 0;
        jj_rescan_token();
        jj_add_error_token(0, 0);
        int[][] exptokseq = new int[this.jj_expentries.size()][];
        for (int i = 0; i < this.jj_expentries.size(); i++) {
            exptokseq[i] = this.jj_expentries.get(i);
        }

        return new ParseException(this.token, exptokseq, ParserConstants.tokenImage,
            this.token_source == null ? null : Lexer.lexStateNames[this.token_source.curLexState]);
    }

    private boolean trace_enabled;

    /**
     * Trace enabled.
     */
    final public boolean trace_enabled() {
        return this.trace_enabled;
    }

    /**
     * Enable tracing.
     */
    final public void enable_tracing() {
    }

    /**
     * Disable tracing.
     */
    final public void disable_tracing() {
    }

    private void jj_rescan_token() {
        this.jj_rescan = true;
        for (int i = 0; i < 10; i++) {
            try {
                JJCalls p = this.jj_2_rtns[i];

                do {
                    if (p.gen > this.jj_gen) {
                        this.jj_la = p.arg;
                        this.jj_lastpos = this.jj_scanpos = p.first;
                        switch (i) {
                            case 0:
                                jj_3_1();
                                break;
                            case 1:
                                jj_3_2();
                                break;
                            case 2:
                                jj_3_3();
                                break;
                            case 3:
                                jj_3_4();
                                break;
                            case 4:
                                jj_3_5();
                                break;
                            case 5:
                                jj_3_6();
                                break;
                            case 6:
                                jj_3_7();
                                break;
                            case 7:
                                jj_3_8();
                                break;
                            case 8:
                                jj_3_9();
                                break;
                            case 9:
                                jj_3_10();
                                break;
                        }
                    }
                    p = p.next;
                } while (p != null);
            } catch (LookaheadSuccess ls) {
            }
        }
        this.jj_rescan = false;
    }

    private void jj_save(int index, int xla) {
        JJCalls p = this.jj_2_rtns[index];
        while (p.gen > this.jj_gen) {
            if (p.next == null) {
                p = p.next = new JJCalls();
                break;
            }
            p = p.next;
        }

        p.gen = (this.jj_gen + xla) - this.jj_la;
        p.first = this.token;
        p.arg = xla;
    }

    static final class JJCalls {

        int     gen;
        Token   first;
        int     arg;
        JJCalls next;
    }

}

// Checksum=8EF93BF8D0BC188EAB993763C2231E59 (Do not edit this line!)
// Options: BASE_PARSER='AbstractJavaCCParser', CACHE_TOKENS=false, DEBUG_LOOKAHEAD=false, DEBUG_PARSER=false, DEPTH_LIMIT=0, ERROR_REPORTING=true, EXPANSIONS=59, EXPANSIONS_PHASE, JAVA_IMPORTS=3, JAVA_IMPORTS_VALUE, JAVA_PACKAGE='org.hivevm.cc.parser', JJ2_INDEX=10, JJ2_OFFSET=10, JJ2_OFFSET_INDEX, JJ2_OFFSET_VALUE, LOOKAHEADS=10, LOOKAHEADS_PHASE, LOOKAHEAD_NEEDED=false, MASK_INDEX=59, NORMALPRODUCTIONS=37, NORMALPRODUCTIONS_PHASE, TOKEN_COUNT=65, TOKEN_MASKS=3, TOKEN_MASKS_INDEX, TOKEN_MASKS_LA1=3, TOKEN_MASKS_LA1_INDEX, TOKEN_MASKS_LA1_VALUE, TOKEN_MASKS_MASK, USE_AST=false
