// Generated by HiveVM Waggle v.1.0 - Do not edit this line!

// Copyright 2024 HiveVM.ORG. All rights reserved.
// Copyright (c) 2006, Sun Microsystems, Inc. All rights reserved.
// SPDX-License-Identifier: BSD-3-Clause
//
// Derived from JavaCC 7.0.12: org/javacc/jjtree/ASTOptions.java, src/main/resources/templates/MultiNode.template

package org.hivevm.waggle.grammar;

public class ASTBNFLookahead extends Node {

    public ASTBNFLookahead(Parser p, int id) {
        super(p, id);
    }

    public Object jjtAccept(NodeVisitor visitor, Object data) {
        return visitor.visit(this, data);
    }
}
// Checksum=F62D41CF2F014AF93925C46FEA8175AE (Do not edit this line!)
// Options: JAVA_PACKAGE='org.hivevm.waggle.grammar', NODE_CLASS='Node', NODE_FACTORY='', NODE_TYPE='ASTBNFLookahead', VISITOR=true, VISITOR_DATA_TYPE='Object', VISITOR_EXCEPTION='', VISITOR_RETURN_TYPE='Object', VISITOR_RETURN_TYPE_VOID=false
