// Generated by HiveVM CC v.1.0 - Do not edit this line!

package org.hivevm.cc.parser.jjtree;

public class ASTBNFZeroOrOne extends ASTNode {

    public ASTBNFZeroOrOne(Parser p, int id) {
        super(p, id);
    }

    public Object jjtAccept(NodeVisitor visitor, ASTWriter data) {
        return visitor.visit(this, data);
    }
}
// Checksum=46C60053B548B4DB21805638B0996FE1 (Do not edit this line!)
// Options: JAVA_PACKAGE='org.hivevm.cc.parser.jjtree', NODE_CLASS='ASTNode', NODE_FACTORY='', NODE_TYPE='ASTBNFZeroOrOne', VISITOR=true, VISITOR_DATA_TYPE='ASTWriter', VISITOR_EXCEPTION='', VISITOR_RETURN_TYPE='Object', VISITOR_RETURN_TYPE_VOID=false
