// Generated by HiveVM CC v.1.0 - Do not edit this line!

package org.hivevm.cc.parser.jjtree;

public class ASTREReference extends ASTNode {

    public ASTREReference(Parser p, int id) {
        super(p, id);
    }

    public Object jjtAccept(NodeVisitor visitor, ASTWriter data) {
        return visitor.visit(this, data);
    }
}
// Checksum=11CD1F5AA261196AF10DE9C19BB2E930 (Do not edit this line!)
// Options: JAVA_PACKAGE='org.hivevm.cc.parser.jjtree', NODE_CLASS='ASTNode', NODE_FACTORY='', NODE_TYPE='ASTREReference', VISITOR=true, VISITOR_DATA_TYPE='ASTWriter', VISITOR_EXCEPTION='', VISITOR_RETURN_TYPE='Object', VISITOR_RETURN_TYPE_VOID=false
