// Generated by HiveVM CC v.1.0 - Do not edit this line!

package org.hivevm.cc.parser.jjtree;

public class ASTREZeroOrMore extends ASTNode {

    public ASTREZeroOrMore(Parser p, int id) {
        super(p, id);
    }

    public Object jjtAccept(NodeVisitor visitor, ASTWriter data) {
        return visitor.visit(this, data);
    }
}
// Checksum=5BE1E1DA9F413CB0DCA9BC1C687CF386 (Do not edit this line!)
// Options: JAVA_PACKAGE='org.hivevm.cc.parser.jjtree', NODE_CLASS='ASTNode', NODE_FACTORY='', NODE_TYPE='ASTREZeroOrMore', VISITOR=true, VISITOR_DATA_TYPE='ASTWriter', VISITOR_EXCEPTION='', VISITOR_RETURN_TYPE='Object', VISITOR_RETURN_TYPE_VOID=false
