// Generated by HiveVM CC v.1.0 - Do not edit this line!

package org.hivevm.cc.parser.jjtree;

public interface NodeVisitor {

    Object visit(Node node, ASTWriter data);

    Object visit(ASTGrammar node, ASTWriter data);

    Object visit(ASTCompilationUnit node, ASTWriter data);

    Object visit(ASTOptionBinding node, ASTWriter data);

    Object visit(ASTBNF node, ASTWriter data);

    Object visit(ASTBNFDeclaration node, ASTWriter data);

    Object visit(ASTBNFNodeScope node, ASTWriter data);

    Object visit(ASTBNFChoice node, ASTWriter data);

    Object visit(ASTBNFSequence node, ASTWriter data);

    Object visit(ASTBNFLookahead node, ASTWriter data);

    Object visit(ASTBNFExpansionScope node, ASTWriter data);

    Object visit(ASTBNFAction node, ASTWriter data);

    Object visit(ASTBNFZeroOrOne node, ASTWriter data);

    Object visit(ASTBNFNonTerminal node, ASTWriter data);

    Object visit(ASTBNFAssignment node, ASTWriter data);

    Object visit(ASTBNFOneOrMore node, ASTWriter data);

    Object visit(ASTBNFZeroOrMore node, ASTWriter data);

    Object visit(ASTBNFParenthesized node, ASTWriter data);

    Object visit(ASTREStringLiteral node, ASTWriter data);

    Object visit(ASTRENamed node, ASTWriter data);

    Object visit(ASTREReference node, ASTWriter data);

    Object visit(ASTREEOF node, ASTWriter data);

    Object visit(ASTREChoice node, ASTWriter data);

    Object visit(ASTRESequence node, ASTWriter data);

    Object visit(ASTREOneOrMore node, ASTWriter data);

    Object visit(ASTREZeroOrMore node, ASTWriter data);

    Object visit(ASTREZeroOrOne node, ASTWriter data);

    Object visit(ASTRRepetitionRange node, ASTWriter data);

    Object visit(ASTREParenthesized node, ASTWriter data);

    Object visit(ASTRECharList node, ASTWriter data);

    Object visit(ASTCharDescriptor node, ASTWriter data);

    Object visit(ASTNodeDescriptor node, ASTWriter data);

    Object visit(ASTExpression node, ASTWriter data);
}
// Checksum=43609581460AB8FBABC8004FFCCEAB8B (Do not edit this line!)
// Options: ARGUMENT_TYPE='ASTWriter', EXCEPTION='', JAVA_PACKAGE='org.hivevm.cc.parser.jjtree', NODES=32, NODES_NAME, NODE_MULTI=true, RETURN_TYPE='Object'
