// Generated by HiveVM CC v.1.0 - Do not edit this line!

package org.hivevm.cc.parser.jjtree;

import java.io.Closeable;
import java.io.IOException;

public interface Provider extends Closeable {

    /**
     * Reads characters into an array
     */
    int read(char[] buffer, int offset, int length) throws IOException;
}
// Checksum=8C8C7938F89E7CF1D55A907BB5EE5AFD (Do not edit this line!)
// Options: JAVA_PACKAGE='org.hivevm.cc.parser.jjtree'
