// Generated by HiveVM CC v.1.0 - Do not edit this line!

package org.hivevm.cc.jjtree;

public class ASTGrammar extends ASTNode {

    public ASTGrammar(Parser p, int id) {
        super(p, id);
    }

    public Object jjtAccept(NodeVisitor visitor, ASTWriter data) {
        return visitor.visit(this, data);
    }
}
// Checksum=E58B3BDD7F5A20ECD0C22768E9897CA7 (Do not edit this line!)
// Options: JAVA_PACKAGE='org.hivevm.cc.jjtree', NODE_CLASS='ASTNode', NODE_FACTORY='', NODE_TYPE='ASTGrammar', VISITOR=true, VISITOR_DATA_TYPE='ASTWriter', VISITOR_EXCEPTION='', VISITOR_RETURN_TYPE='Object', VISITOR_RETURN_TYPE_VOID=false
