// Generated by HiveVM CC v.1.0 - Do not edit this line!

package org.hivevm.cc.jjtree;

public class NodeDefaultVisitor implements NodeVisitor {

    public Object defaultVisit(Node node, ASTWriter data) {
        node.childrenAccept(this, data);
        return null;
    }

    public Object visit(Node node, ASTWriter data) {
        return defaultVisit(node, data);
    }

    public Object visit(ASTGrammar node, ASTWriter data) {
        return defaultVisit(node, data);
    }

    public Object visit(ASTCompilationUnit node, ASTWriter data) {
        return defaultVisit(node, data);
    }

    public Object visit(ASTOptionBinding node, ASTWriter data) {
        return defaultVisit(node, data);
    }

    public Object visit(ASTBNF node, ASTWriter data) {
        return defaultVisit(node, data);
    }

    public Object visit(ASTBNFDeclaration node, ASTWriter data) {
        return defaultVisit(node, data);
    }

    public Object visit(ASTBNFNodeScope node, ASTWriter data) {
        return defaultVisit(node, data);
    }

    public Object visit(ASTBNFChoice node, ASTWriter data) {
        return defaultVisit(node, data);
    }

    public Object visit(ASTBNFSequence node, ASTWriter data) {
        return defaultVisit(node, data);
    }

    public Object visit(ASTBNFLookahead node, ASTWriter data) {
        return defaultVisit(node, data);
    }

    public Object visit(ASTBNFExpansionScope node, ASTWriter data) {
        return defaultVisit(node, data);
    }

    public Object visit(ASTBNFAction node, ASTWriter data) {
        return defaultVisit(node, data);
    }

    public Object visit(ASTBNFZeroOrOne node, ASTWriter data) {
        return defaultVisit(node, data);
    }

    public Object visit(ASTBNFNonTerminal node, ASTWriter data) {
        return defaultVisit(node, data);
    }

    public Object visit(ASTBNFAssignment node, ASTWriter data) {
        return defaultVisit(node, data);
    }

    public Object visit(ASTBNFOneOrMore node, ASTWriter data) {
        return defaultVisit(node, data);
    }

    public Object visit(ASTBNFZeroOrMore node, ASTWriter data) {
        return defaultVisit(node, data);
    }

    public Object visit(ASTBNFParenthesized node, ASTWriter data) {
        return defaultVisit(node, data);
    }

    public Object visit(ASTREStringLiteral node, ASTWriter data) {
        return defaultVisit(node, data);
    }

    public Object visit(ASTRENamed node, ASTWriter data) {
        return defaultVisit(node, data);
    }

    public Object visit(ASTREReference node, ASTWriter data) {
        return defaultVisit(node, data);
    }

    public Object visit(ASTREEOF node, ASTWriter data) {
        return defaultVisit(node, data);
    }

    public Object visit(ASTREChoice node, ASTWriter data) {
        return defaultVisit(node, data);
    }

    public Object visit(ASTRESequence node, ASTWriter data) {
        return defaultVisit(node, data);
    }

    public Object visit(ASTREOneOrMore node, ASTWriter data) {
        return defaultVisit(node, data);
    }

    public Object visit(ASTREZeroOrMore node, ASTWriter data) {
        return defaultVisit(node, data);
    }

    public Object visit(ASTREZeroOrOne node, ASTWriter data) {
        return defaultVisit(node, data);
    }

    public Object visit(ASTRRepetitionRange node, ASTWriter data) {
        return defaultVisit(node, data);
    }

    public Object visit(ASTREParenthesized node, ASTWriter data) {
        return defaultVisit(node, data);
    }

    public Object visit(ASTRECharList node, ASTWriter data) {
        return defaultVisit(node, data);
    }

    public Object visit(ASTCharDescriptor node, ASTWriter data) {
        return defaultVisit(node, data);
    }

    public Object visit(ASTNodeDescriptor node, ASTWriter data) {
        return defaultVisit(node, data);
    }

    public Object visit(ASTExpression node, ASTWriter data) {
        return defaultVisit(node, data);
    }
}
// Checksum=A86D3621B87B59F89486C7070F7B36FF (Do not edit this line!)
// Options: ARGUMENT_TYPE='ASTWriter', EXCEPTION='', JAVA_PACKAGE='org.hivevm.cc.jjtree', NODES=32, NODES_NAME, NODE_MULTI=true, RETURN='return ', RETURN_TYPE='Object', RETURN_VALUE=' null'
