// Generated by HiveVM CC v.1.0 - Do not edit this line!

package org.hivevm.cc.jjtree;

public interface NodeType {
    int JJTGRAMMAR = 0;
    int JJTCOMPILATIONUNIT = 1;
    int JJTOPTIONBINDING = 2;
    int JJTBNF = 3;
    int JJTBNFDECLARATION = 4;
    int JJTBNFNODESCOPE = 5;
    int JJTBNFCHOICE = 6;
    int JJTBNFSEQUENCE = 7;
    int JJTBNFLOOKAHEAD = 8;
    int JJTBNFEXPANSIONSCOPE = 9;
    int JJTBNFACTION = 10;
    int JJTBNFZEROORONE = 11;
    int JJTBNFNONTERMINAL = 12;
    int JJTBNFASSIGNMENT = 13;
    int JJTBNFONEORMORE = 14;
    int JJTBNFZEROORMORE = 15;
    int JJTBNFPARENTHESIZED = 16;
    int JJTRESTRINGLITERAL = 17;
    int JJTRENAMED = 18;
    int JJTREREFERENCE = 19;
    int JJTREEOF = 20;
    int JJTRECHOICE = 21;
    int JJTRESEQUENCE = 22;
    int JJTREONEORMORE = 23;
    int JJTREZEROORMORE = 24;
    int JJTREZEROORONE = 25;
    int JJTRREPETITIONRANGE = 26;
    int JJTREPARENTHESIZED = 27;
    int JJTRECHARLIST = 28;
    int JJTCHARDESCRIPTOR = 29;
    int JJTNODEDESCRIPTOR = 30;
    int JJTEXPRESSION = 31;


    String[] jjtNodeName = {
        "Grammar",
        "CompilationUnit",
        "OptionBinding",
        "BNF",
        "BNFDeclaration",
        "BNFNodeScope",
        "BNFChoice",
        "BNFSequence",
        "BNFLookahead",
        "BNFExpansionScope",
        "BNFAction",
        "BNFZeroOrOne",
        "BNFNonTerminal",
        "BNFAssignment",
        "BNFOneOrMore",
        "BNFZeroOrMore",
        "BNFParenthesized",
        "REStringLiteral",
        "RENamed",
        "REReference",
        "REEOF",
        "REChoice",
        "RESequence",
        "REOneOrMore",
        "REZeroOrMore",
        "REZeroOrOne",
        "RRepetitionRange",
        "REParenthesized",
        "RECharList",
        "CharDescriptor",
        "NodeDescriptor",
        "Expression",
    };
}

// Checksum=B09D6096941241878C5A0020718BADDA (Do not edit this line!)
// Options: JAVA_PACKAGE='org.hivevm.cc.jjtree', NODES=32, NODES_LABEL, NODES_ORDINAL, NODE_NAMES=32, NODE_NAMES_TITLE
