// Generated by HiveVM CC v.1.0 - Do not edit this line!

package org.hivevm.cc.jjtree;

import org.hivevm.cc.model.NodeScope;

public class Parser
    extends ASTParser
    implements ParserConstants {

    private final NodeState jjtree = new NodeState();

/************************************************
 * THE JAVACC GRAMMAR SPECIFICATION STARTS HERE *
 ************************************************/
  public final void javacc_input() throws ParseException {  // Grammar
  ASTGrammar jjtn000 = new ASTGrammar(this, NodeType.JJTGRAMMAR);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);
  jjtreeOpenNodeScope(jjtn000);
  try {

    // #CompilationUnit(true)
    ASTCompilationUnit jjtn001 = new ASTCompilationUnit(this, NodeType.JJTCOMPILATIONUNIT);
    boolean jjtc001 = true;
    jjtree.openNodeScope(jjtn001);
    jjtreeOpenNodeScope(jjtn001);
    try {
    
    jj_consume_token(_PARSER);
    jj_consume_token(LPAREN);
    option_binding();
    label_1:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case COMMA:{
        ;
        break;
        }
      default:
        jj_la1[0] = jj_gen;
        break label_1;
      }
      jj_consume_token(COMMA);
      option_binding();
    }
    jj_consume_token(RPAREN);
    } catch (Throwable jjte001) {
      if (jjtc001) {
        jjtree.clearNodeScope(jjtn001);
        jjtc001 = false;
      } else {
        jjtree.popNode();
      }
      if (jjte001 instanceof RuntimeException) {
        throw (RuntimeException)jjte001;
      }
      if (jjte001 instanceof ParseException) {
        throw (ParseException)jjte001;
      }
      throw (Error)jjte001;
    } finally {
      if (jjtc001) {
    jjtree.closeNodeScope(jjtn001, true);
    if (jjtree.nodeCreated()) {
     jjtreeCloseNodeScope(jjtn001);
    }
      }
    }
    label_2:
    while (true) {
      bnf_production();
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case _RULE:{
        ;
        break;
        }
      default:
        jj_la1[1] = jj_gen;
        break label_2;
      }
    }
    jj_consume_token(0);
} catch (Throwable jjte000) {
    if (jjtc000) {
      jjtree.clearNodeScope(jjtn000);
      jjtc000 = false;
    } else {
      jjtree.popNode();
    }
    if (jjte000 instanceof RuntimeException) {
      throw (RuntimeException)jjte000;
    }
    if (jjte000 instanceof ParseException) {
      throw (ParseException)jjte000;
    }
    throw (Error)jjte000;
  } finally {
    if (jjtc000) {
  jjtree.closeNodeScope(jjtn000, true);
  if (jjtree.nodeCreated()) {
   jjtreeCloseNodeScope(jjtn000);
  }
    }
  }
}


  public final void option_binding() throws ParseException {  // OptionBinding
  ASTOptionBinding jjtn000 = new ASTOptionBinding(this, NodeType.JJTOPTIONBINDING);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);
  jjtreeOpenNodeScope(jjtn000);
  try {

 Token t; 
    t = jj_consume_token(IDENTIFIER);
    jj_consume_token(COLON);
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case INTEGER_LITERAL:{
      IntegerLiteral();
      break;
      }
    case TRUE:
    case FALSE:{
      BooleanLiteral();
      break;
      }
    case STRING_LITERAL:{
      StringLiteral();
      break;
      }
    default:
      jj_la1[2] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
jjtree.closeNodeScope(jjtn000, true);
    jjtc000 = false;
    if (jjtree.nodeCreated()) {
     jjtreeCloseNodeScope(jjtn000);
    }
 setInputOption(t, this.token); 
} catch (Throwable jjte000) {
    if (jjtc000) {
      jjtree.clearNodeScope(jjtn000);
      jjtc000 = false;
    } else {
      jjtree.popNode();
    }
    if (jjte000 instanceof RuntimeException) {
      throw (RuntimeException)jjte000;
    }
    if (jjte000 instanceof ParseException) {
      throw (ParseException)jjte000;
    }
    throw (Error)jjte000;
  } finally {
    if (jjtc000) {
  jjtree.closeNodeScope(jjtn000, true);
  if (jjtree.nodeCreated()) {
   jjtreeCloseNodeScope(jjtn000);
  }
    }
  }
}


  public final void bnf_production() throws ParseException {  // BNF
  ASTBNF jjtn000 = new ASTBNF(this, NodeType.JJTBNF);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);
  jjtreeOpenNodeScope(jjtn000);
  try {


    Token t1;
    ASTBNF prod = jjtn000;
    ASTNodeDescriptor nd = null;
    JJTNodeScope ns;
    ASTNode eu;

    jj_consume_token(_RULE);
    t1 = identifier();
    jj_consume_token(LPAREN);
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case _LOOKAHEAD:
    case _IGNORE_CASE:
    case _PARSER:
    case _TOKEN:
    case _SPECIAL_TOKEN:
    case _MORE:
    case _SKIP:
    case _EOF:
    case BOOLEAN:
    case INT:
    case CHAR:
    case IDENTIFIER:{
      FormalParameter();
      label_3:
      while (true) {
        switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
        case COMMA:{
          ;
          break;
          }
        default:
          jj_la1[3] = jj_gen;
          break label_3;
        }
        jj_consume_token(COMMA);
        FormalParameter();
      }
      break;
      }
    default:
      jj_la1[4] = jj_gen;
      ;
    }
    jj_consume_token(RPAREN);
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case COLON:{
      jj_consume_token(COLON);
      Type();
      break;
      }
    default:
      jj_la1[5] = jj_gen;
      ;
    }
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case HASH:{
      nd = node_descriptor();
      break;
      }
    default:
      jj_la1[6] = jj_gen;
      ;
    }

	prod.setName(t1.image);
	ns = new JJTNodeScope(prod, nd);

    // BNFDeclaration
    ASTBNFDeclaration jjtn001 = new ASTBNFDeclaration(this, NodeType.JJTBNFDECLARATION);
    boolean jjtc001 = true;
    jjtree.openNodeScope(jjtn001);
    jjtreeOpenNodeScope(jjtn001);
    try {
    
jjtree.closeNodeScope(jjtn001, true);
      jjtc001 = false;
      if (jjtree.nodeCreated()) {
       jjtreeCloseNodeScope(jjtn001);
      }
 jjtn001.node_scope = ns;
    } finally {
      if (jjtc001) {
    jjtree.closeNodeScope(jjtn001, true);
    if (jjtree.nodeCreated()) {
     jjtreeCloseNodeScope(jjtn001);
    }
      }
    }
    jj_consume_token(ASSIGN_OP);
    // BNFNodeScope
    ASTBNFNodeScope jjtn002 = new ASTBNFNodeScope(this, NodeType.JJTBNFNODESCOPE);
    boolean jjtc002 = true;
    jjtree.openNodeScope(jjtn002);
    jjtreeOpenNodeScope(jjtn002);
    try {
    
    eu = expansion_choices(prod);
jjtree.closeNodeScope(jjtn002, true);
  jjtc002 = false;
  if (jjtree.nodeCreated()) {
   jjtreeCloseNodeScope(jjtn002);
  }

	  jjtn002.node_scope = ns;
	  jjtn002.expansion_unit = eu;

} catch (Throwable jjte002) {
      if (jjtc002) {
        jjtree.clearNodeScope(jjtn002);
        jjtc002 = false;
      } else {
        jjtree.popNode();
      }
      if (jjte002 instanceof RuntimeException) {
        throw (RuntimeException)jjte002;
      }
      if (jjte002 instanceof ParseException) {
        throw (ParseException)jjte002;
      }
      throw (Error)jjte002;
    } finally {
      if (jjtc002) {
    jjtree.closeNodeScope(jjtn002, true);
    if (jjtree.nodeCreated()) {
     jjtreeCloseNodeScope(jjtn002);
    }
      }
    }
    jj_consume_token(RBRACE);
    jj_consume_token(SEMICOLON);
jjtree.closeNodeScope(jjtn000, true);
    jjtc000 = false;
    if (jjtree.nodeCreated()) {
     jjtreeCloseNodeScope(jjtn000);
    }
 addProduction(prod); 
} catch (Throwable jjte000) {
    if (jjtc000) {
      jjtree.clearNodeScope(jjtn000);
      jjtc000 = false;
    } else {
      jjtree.popNode();
    }
    if (jjte000 instanceof RuntimeException) {
      throw (RuntimeException)jjte000;
    }
    if (jjte000 instanceof ParseException) {
      throw (ParseException)jjte000;
    }
    throw (Error)jjte000;
  } finally {
    if (jjtc000) {
  jjtree.closeNodeScope(jjtn000, true);
  if (jjtree.nodeCreated()) {
   jjtreeCloseNodeScope(jjtn000);
  }
    }
  }
}


  public final                                           ASTNode expansion_choices(ASTProduction p) throws ParseException {  // #BNFChoice(>1)
  ASTBNFChoice jjtn000 = new ASTBNFChoice(this, NodeType.JJTBNFCHOICE);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);
  jjtreeOpenNodeScope(jjtn000);
  try {

    expansion(p);
    label_4:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case BIT_OR:{
        ;
        break;
        }
      default:
        jj_la1[7] = jj_gen;
        break label_4;
      }
      jj_consume_token(BIT_OR);
      expansion(p);
    }
jjtree.closeNodeScope(jjtn000, jjtree.nodeArity() >1);
    jjtc000 = false;
    if (jjtree.nodeCreated()) {
     jjtreeCloseNodeScope(jjtn000);
    }
 return (ASTNode)jjtree.peekNode(); 
} catch (Throwable jjte000) {
    if (jjtc000) {
      jjtree.clearNodeScope(jjtn000);
      jjtc000 = false;
    } else {
      jjtree.popNode();
    }
    if (jjte000 instanceof RuntimeException) {
      throw (RuntimeException)jjte000;
    }
    if (jjte000 instanceof ParseException) {
      throw (ParseException)jjte000;
    }
    throw (Error)jjte000;
  } finally {
    if (jjtc000) {
  jjtree.closeNodeScope(jjtn000, jjtree.nodeArity() >1);
  if (jjtree.nodeCreated()) {
   jjtreeCloseNodeScope(jjtn000);
  }
    }
  }
}


  public final void expansion(ASTProduction p) throws ParseException {  // #BNFSequence(>1)
  ASTBNFSequence jjtn000 = new ASTBNFSequence(this, NodeType.JJTBNFSEQUENCE);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);
  jjtreeOpenNodeScope(jjtn000);
  try {


    ASTNode eu;
    ASTNodeDescriptor nd = null;

    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case _LOOKAHEAD:{
      // BNFLookahead
      ASTBNFLookahead jjtn001 = new ASTBNFLookahead(this, NodeType.JJTBNFLOOKAHEAD);
      boolean jjtc001 = true;
      jjtree.openNodeScope(jjtn001);
      jjtreeOpenNodeScope(jjtn001);
      try {
      
      jj_consume_token(_LOOKAHEAD);
      jj_consume_token(LPAREN);
      local_lookahead(p);
      jj_consume_token(RPAREN);
      } catch (Throwable jjte001) {
        if (jjtc001) {
          jjtree.clearNodeScope(jjtn001);
          jjtc001 = false;
        } else {
          jjtree.popNode();
        }
        if (jjte001 instanceof RuntimeException) {
          throw (RuntimeException)jjte001;
        }
        if (jjte001 instanceof ParseException) {
          throw (ParseException)jjte001;
        }
        throw (Error)jjte001;
      } finally {
        if (jjtc001) {
      jjtree.closeNodeScope(jjtn001, true);
      if (jjtree.nodeCreated()) {
       jjtreeCloseNodeScope(jjtn001);
      }
        }
      }
      break;
      }
    default:
      jj_la1[8] = jj_gen;
      ;
    }
    label_5:
    while (true) {
      // #BNFExpansionScope(>1)
      ASTBNFExpansionScope jjtn002 = new ASTBNFExpansionScope(this, NodeType.JJTBNFEXPANSIONSCOPE);
      boolean jjtc002 = true;
      jjtree.openNodeScope(jjtn002);
      jjtreeOpenNodeScope(jjtn002);
      try {
      
      eu = expansion_unit(p);
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case HASH:{
        nd = node_descriptor();
        break;
        }
      default:
        jj_la1[9] = jj_gen;
        ;
      }
jjtree.closeNodeScope(jjtn002, jjtree.nodeArity() >1);
  jjtc002 = false;
  if (jjtree.nodeCreated()) {
   jjtreeCloseNodeScope(jjtn002);
  }

	    if (jjtree.nodeCreated()) {
	      jjtn002.node_scope = new JJTNodeScope(p, nd);
	      jjtn002.expansion_unit = eu;
	    }

      } catch (Throwable jjte002) {
        if (jjtc002) {
          jjtree.clearNodeScope(jjtn002);
          jjtc002 = false;
        } else {
          jjtree.popNode();
        }
        if (jjte002 instanceof RuntimeException) {
          throw (RuntimeException)jjte002;
        }
        if (jjte002 instanceof ParseException) {
          throw (ParseException)jjte002;
        }
        throw (Error)jjte002;
      } finally {
        if (jjtc002) {
      jjtree.closeNodeScope(jjtn002, jjtree.nodeArity() >1);
      if (jjtree.nodeCreated()) {
       jjtreeCloseNodeScope(jjtn002);
      }
        }
      }
      if (notTailOfExpansionUnit()) {
        ;
      } else {
        break label_5;
      }
    }
} catch (Throwable jjte000) {
    if (jjtc000) {
      jjtree.clearNodeScope(jjtn000);
      jjtc000 = false;
    } else {
      jjtree.popNode();
    }
    if (jjte000 instanceof RuntimeException) {
      throw (RuntimeException)jjte000;
    }
    if (jjte000 instanceof ParseException) {
      throw (ParseException)jjte000;
    }
    throw (Error)jjte000;
  } finally {
    if (jjtc000) {
  jjtree.closeNodeScope(jjtn000, jjtree.nodeArity() >1);
  if (jjtree.nodeCreated()) {
   jjtreeCloseNodeScope(jjtn000);
  }
    }
  }
}


  public final void local_lookahead(ASTProduction p) throws ParseException {

    boolean commaAtEnd = false;
    boolean emptyLA = true;

    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case INTEGER_LITERAL:{
      IntegerLiteral();
 emptyLA = false; 
      break;
      }
    default:
      jj_la1[10] = jj_gen;
      ;
    }
    if (checkEmptyLA(emptyLA, getToken(1))) {
      jj_consume_token(COMMA);
 commaAtEnd = true; 
    } else {
      ;
    }
    if (checkEmpty(getToken(1))) {
      expansion_choices(p);
 emptyLA = false; commaAtEnd = false; 
    } else {
      ;
    }
    if (checkEmptyLAAndCommandEnd(emptyLA, commaAtEnd, getToken(1))) {
      jj_consume_token(COMMA);
 commaAtEnd = true; 
    } else {
      ;
    }
    if (checkEmptyLAOrCommandEnd(emptyLA, commaAtEnd)) {
      jj_consume_token(LBRACE);
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case _LOOKAHEAD:
      case _IGNORE_CASE:
      case _PARSER:
      case _TOKEN:
      case _SPECIAL_TOKEN:
      case _MORE:
      case _SKIP:
      case _EOF:
      case NULL:
      case TRUE:
      case FALSE:
      case INTEGER_LITERAL:
      case FLOATING_POINT_LITERAL:
      case CHARACTER_LITERAL:
      case STRING_LITERAL:
      case LPAREN:
      case IDENTIFIER:{
        Expression();
        break;
        }
      default:
        jj_la1[11] = jj_gen;
        ;
      }
      jj_consume_token(RBRACE);
    } else {
      ;
    }
}


  public final                                        ASTNode expansion_unit(ASTProduction p) throws ParseException {
 Token t; 
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case _LOOKAHEAD:{
      // BNFLookahead
      ASTBNFLookahead jjtn000 = new ASTBNFLookahead(this, NodeType.JJTBNFLOOKAHEAD);
      boolean jjtc000 = true;
      jjtree.openNodeScope(jjtn000);
      jjtreeOpenNodeScope(jjtn000);
      try {
      
      jj_consume_token(_LOOKAHEAD);
      jj_consume_token(LPAREN);
      local_lookahead(p);
      jj_consume_token(RPAREN);
      } catch (Throwable jjte000) {
        if (jjtc000) {
          jjtree.clearNodeScope(jjtn000);
          jjtc000 = false;
        } else {
          jjtree.popNode();
        }
        if (jjte000 instanceof RuntimeException) {
          throw (RuntimeException)jjte000;
        }
        if (jjte000 instanceof ParseException) {
          throw (ParseException)jjte000;
        }
        throw (Error)jjte000;
      } finally {
        if (jjtc000) {
      jjtree.closeNodeScope(jjtn000, true);
      if (jjtree.nodeCreated()) {
       jjtreeCloseNodeScope(jjtn000);
      }
        }
      }
      break;
      }
    case ECODE_DATA:
    case LBRACE:{
      // BNFAction
      ASTBNFAction jjtn001 = new ASTBNFAction(this, NodeType.JJTBNFACTION);
      boolean jjtc001 = true;
      jjtree.openNodeScope(jjtn001);
      jjtreeOpenNodeScope(jjtn001);
      try {
      
      Statement();
      } catch (Throwable jjte001) {
        if (jjtc001) {
          jjtree.clearNodeScope(jjtn001);
          jjtc001 = false;
        } else {
          jjtree.popNode();
        }
        if (jjte001 instanceof RuntimeException) {
          throw (RuntimeException)jjte001;
        }
        if (jjte001 instanceof ParseException) {
          throw (ParseException)jjte001;
        }
        throw (Error)jjte001;
      } finally {
        if (jjtc001) {
      jjtree.closeNodeScope(jjtn001, true);
      if (jjtree.nodeCreated()) {
       jjtreeCloseNodeScope(jjtn001);
      }
        }
      }
      break;
      }
    case LBRACKET:{
      // BNFZeroOrOne
      ASTBNFZeroOrOne jjtn002 = new ASTBNFZeroOrOne(this, NodeType.JJTBNFZEROORONE);
      boolean jjtc002 = true;
      jjtree.openNodeScope(jjtn002);
      jjtreeOpenNodeScope(jjtn002);
      try {
      
      jj_consume_token(LBRACKET);
      expansion_choices(p);
      jj_consume_token(RBRACKET);
      } catch (Throwable jjte002) {
        if (jjtc002) {
          jjtree.clearNodeScope(jjtn002);
          jjtc002 = false;
        } else {
          jjtree.popNode();
        }
        if (jjte002 instanceof RuntimeException) {
          throw (RuntimeException)jjte002;
        }
        if (jjte002 instanceof ParseException) {
          throw (ParseException)jjte002;
        }
        throw (Error)jjte002;
      } finally {
        if (jjtc002) {
      jjtree.closeNodeScope(jjtn002, true);
      if (jjtree.nodeCreated()) {
       jjtreeCloseNodeScope(jjtn002);
      }
        }
      }
      break;
      }
    default:
      jj_la1[15] = jj_gen;
      if (jj_2_2(2147483647)) {
        // #BNFAssignment(>1)
        ASTBNFAssignment jjtn004 = new ASTBNFAssignment(this, NodeType.JJTBNFASSIGNMENT);
        boolean jjtc004 = true;
        jjtree.openNodeScope(jjtn004);
        jjtreeOpenNodeScope(jjtn004);
        try {
        
        if (jj_2_1(2147483647)) {
          Expression();
          jj_consume_token(ASSIGN);
        } else {
          ;
        }
        switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
        case STRING_LITERAL:
        case LT:{
          regular_expression();
          switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
          case DOT:{
            jj_consume_token(DOT);
            t = jj_consume_token(IDENTIFIER);
            break;
            }
          default:
            jj_la1[12] = jj_gen;
            ;
          }
          break;
          }
        case IDENTIFIER:{
          // BNFNonTerminal
          ASTBNFNonTerminal jjtn003 = new ASTBNFNonTerminal(this, NodeType.JJTBNFNONTERMINAL);
          boolean jjtc003 = true;
          jjtree.openNodeScope(jjtn003);
          jjtreeOpenNodeScope(jjtn003);
          try {
          
          identifier();
          Arguments();
          } catch (Throwable jjte003) {
            if (jjtc003) {
              jjtree.clearNodeScope(jjtn003);
              jjtc003 = false;
            } else {
              jjtree.popNode();
            }
            if (jjte003 instanceof RuntimeException) {
              throw (RuntimeException)jjte003;
            }
            if (jjte003 instanceof ParseException) {
              throw (ParseException)jjte003;
            }
            throw (Error)jjte003;
          } finally {
            if (jjtc003) {
          jjtree.closeNodeScope(jjtn003, true);
          if (jjtree.nodeCreated()) {
           jjtreeCloseNodeScope(jjtn003);
          }
            }
          }
          break;
          }
        default:
          jj_la1[13] = jj_gen;
          jj_consume_token(-1);
          throw new ParseException();
        }
        } catch (Throwable jjte004) {
          if (jjtc004) {
            jjtree.clearNodeScope(jjtn004);
            jjtc004 = false;
          } else {
            jjtree.popNode();
          }
          if (jjte004 instanceof RuntimeException) {
            throw (RuntimeException)jjte004;
          }
          if (jjte004 instanceof ParseException) {
            throw (ParseException)jjte004;
          }
          throw (Error)jjte004;
        } finally {
          if (jjtc004) {
        jjtree.closeNodeScope(jjtn004, jjtree.nodeArity() >1);
        if (jjtree.nodeCreated()) {
         jjtreeCloseNodeScope(jjtn004);
        }
          }
        }
      } else {
        switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
        case LPAREN:{
          t = jj_consume_token(LPAREN);
          expansion_choices(p);
          jj_consume_token(RPAREN);
          switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
          case PLUS:{
            // #BNFOneOrMore(1)
            ASTBNFOneOrMore jjtn005 = new ASTBNFOneOrMore(this, NodeType.JJTBNFONEORMORE);
            boolean jjtc005 = true;
            jjtree.openNodeScope(jjtn005);
            jjtreeOpenNodeScope(jjtn005);
            try {
            
            jj_consume_token(PLUS);
            } finally {
              if (jjtc005) {
            jjtree.closeNodeScope(jjtn005, 1);
            if (jjtree.nodeCreated()) {
             jjtreeCloseNodeScope(jjtn005);
            }
              }
            }
            break;
            }
          case STAR:{
            // #BNFZeroOrMore(1)
            ASTBNFZeroOrMore jjtn006 = new ASTBNFZeroOrMore(this, NodeType.JJTBNFZEROORMORE);
            boolean jjtc006 = true;
            jjtree.openNodeScope(jjtn006);
            jjtreeOpenNodeScope(jjtn006);
            try {
            
            jj_consume_token(STAR);
            } finally {
              if (jjtc006) {
            jjtree.closeNodeScope(jjtn006, 1);
            if (jjtree.nodeCreated()) {
             jjtreeCloseNodeScope(jjtn006);
            }
              }
            }
            break;
            }
          case HOOK:{
            // #BNFZeroOrOne(1)
            ASTBNFZeroOrOne jjtn007 = new ASTBNFZeroOrOne(this, NodeType.JJTBNFZEROORONE);
            boolean jjtc007 = true;
            jjtree.openNodeScope(jjtn007);
            jjtreeOpenNodeScope(jjtn007);
            try {
            
            jj_consume_token(HOOK);
            } finally {
              if (jjtc007) {
            jjtree.closeNodeScope(jjtn007, 1);
            if (jjtree.nodeCreated()) {
             jjtreeCloseNodeScope(jjtn007);
            }
              }
            }
            break;
            }
          default:
            jj_la1[14] = jj_gen;
            // #BNFParenthesized(1)
            ASTBNFParenthesized jjtn008 = new ASTBNFParenthesized(this, NodeType.JJTBNFPARENTHESIZED);
            boolean jjtc008 = true;
            jjtree.openNodeScope(jjtn008);
            jjtreeOpenNodeScope(jjtn008);
            try {
            
jjtree.closeNodeScope(jjtn008, 1);
      jjtc008 = false;
      if (jjtree.nodeCreated()) {
       jjtreeCloseNodeScope(jjtn008);
      }

            } finally {
              if (jjtc008) {
            jjtree.closeNodeScope(jjtn008, 1);
            if (jjtree.nodeCreated()) {
             jjtreeCloseNodeScope(jjtn008);
            }
              }
            }
          }
 ((ASTNode)jjtree.peekNode()).setFirstToken(t); 
          break;
          }
        default:
          jj_la1[16] = jj_gen;
          jj_consume_token(-1);
          throw new ParseException();
        }
      }
    }
 return (ASTNode)jjtree.peekNode(); 
}


  public final void regular_expression() throws ParseException {
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case STRING_LITERAL:{
      // REStringLiteral
      ASTREStringLiteral jjtn000 = new ASTREStringLiteral(this, NodeType.JJTRESTRINGLITERAL);
      boolean jjtc000 = true;
      jjtree.openNodeScope(jjtn000);
      jjtreeOpenNodeScope(jjtn000);
      try {
      
      StringLiteral();
      } catch (Throwable jjte000) {
        if (jjtc000) {
          jjtree.clearNodeScope(jjtn000);
          jjtc000 = false;
        } else {
          jjtree.popNode();
        }
        if (jjte000 instanceof RuntimeException) {
          throw (RuntimeException)jjte000;
        }
        if (jjte000 instanceof ParseException) {
          throw (ParseException)jjte000;
        }
        throw (Error)jjte000;
      } finally {
        if (jjtc000) {
      jjtree.closeNodeScope(jjtn000, true);
      if (jjtree.nodeCreated()) {
       jjtreeCloseNodeScope(jjtn000);
      }
        }
      }
      break;
      }
    default:
      jj_la1[19] = jj_gen;
      if (jj_2_3(3)) {
        // RENamed
        ASTRENamed jjtn001 = new ASTRENamed(this, NodeType.JJTRENAMED);
        boolean jjtc001 = true;
        jjtree.openNodeScope(jjtn001);
        jjtreeOpenNodeScope(jjtn001);
        try {
        
        jj_consume_token(LT);
        switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
        case HASH:
        case IDENTIFIER:{
          switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
          case HASH:{
            jj_consume_token(HASH);
            break;
            }
          default:
            jj_la1[17] = jj_gen;
            ;
          }
          identifier();
          jj_consume_token(COLON);
          break;
          }
        default:
          jj_la1[18] = jj_gen;
          ;
        }
        complex_regular_expression_choices();
        jj_consume_token(GT);
        } catch (Throwable jjte001) {
          if (jjtc001) {
            jjtree.clearNodeScope(jjtn001);
            jjtc001 = false;
          } else {
            jjtree.popNode();
          }
          if (jjte001 instanceof RuntimeException) {
            throw (RuntimeException)jjte001;
          }
          if (jjte001 instanceof ParseException) {
            throw (ParseException)jjte001;
          }
          throw (Error)jjte001;
        } finally {
          if (jjtc001) {
        jjtree.closeNodeScope(jjtn001, true);
        if (jjtree.nodeCreated()) {
         jjtreeCloseNodeScope(jjtn001);
        }
          }
        }
      } else if (jj_2_4(2)) {
        // REReference
        ASTREReference jjtn002 = new ASTREReference(this, NodeType.JJTREREFERENCE);
        boolean jjtc002 = true;
        jjtree.openNodeScope(jjtn002);
        jjtreeOpenNodeScope(jjtn002);
        try {
        
        jj_consume_token(LT);
        identifier();
        jj_consume_token(GT);
        } catch (Throwable jjte002) {
          if (jjtc002) {
            jjtree.clearNodeScope(jjtn002);
            jjtc002 = false;
          } else {
            jjtree.popNode();
          }
          if (jjte002 instanceof RuntimeException) {
            throw (RuntimeException)jjte002;
          }
          if (jjte002 instanceof ParseException) {
            throw (ParseException)jjte002;
          }
          throw (Error)jjte002;
        } finally {
          if (jjtc002) {
        jjtree.closeNodeScope(jjtn002, true);
        if (jjtree.nodeCreated()) {
         jjtreeCloseNodeScope(jjtn002);
        }
          }
        }
      } else {
        switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
        case LT:{
          // REEOF
          ASTREEOF jjtn003 = new ASTREEOF(this, NodeType.JJTREEOF);
          boolean jjtc003 = true;
          jjtree.openNodeScope(jjtn003);
          jjtreeOpenNodeScope(jjtn003);
          try {
          
          jj_consume_token(LT);
          jj_consume_token(_EOF);
          jj_consume_token(GT);
          } catch (Throwable jjte003) {
            if (jjtc003) {
              jjtree.clearNodeScope(jjtn003);
              jjtc003 = false;
            } else {
              jjtree.popNode();
            }
            if (jjte003 instanceof RuntimeException) {
              throw (RuntimeException)jjte003;
            }
            if (jjte003 instanceof ParseException) {
              throw (ParseException)jjte003;
            }
            throw (Error)jjte003;
          } finally {
            if (jjtc003) {
          jjtree.closeNodeScope(jjtn003, true);
          if (jjtree.nodeCreated()) {
           jjtreeCloseNodeScope(jjtn003);
          }
            }
          }
          break;
          }
        default:
          jj_la1[20] = jj_gen;
          jj_consume_token(-1);
          throw new ParseException();
        }
      }
    }
}


  public final void complex_regular_expression_choices() throws ParseException {  // #REChoice(>1)
  ASTREChoice jjtn000 = new ASTREChoice(this, NodeType.JJTRECHOICE);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);
  jjtreeOpenNodeScope(jjtn000);
  try {

    complex_regular_expression();
    label_6:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case BIT_OR:{
        ;
        break;
        }
      default:
        jj_la1[21] = jj_gen;
        break label_6;
      }
      jj_consume_token(BIT_OR);
      complex_regular_expression();
    }
} catch (Throwable jjte000) {
    if (jjtc000) {
      jjtree.clearNodeScope(jjtn000);
      jjtc000 = false;
    } else {
      jjtree.popNode();
    }
    if (jjte000 instanceof RuntimeException) {
      throw (RuntimeException)jjte000;
    }
    if (jjte000 instanceof ParseException) {
      throw (ParseException)jjte000;
    }
    throw (Error)jjte000;
  } finally {
    if (jjtc000) {
  jjtree.closeNodeScope(jjtn000, jjtree.nodeArity() >1);
  if (jjtree.nodeCreated()) {
   jjtreeCloseNodeScope(jjtn000);
  }
    }
  }
}


  public final void complex_regular_expression() throws ParseException {  // #RESequence(>1)
  ASTRESequence jjtn000 = new ASTRESequence(this, NodeType.JJTRESEQUENCE);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);
  jjtreeOpenNodeScope(jjtn000);
  try {

    label_7:
    while (true) {
      complex_regular_expression_unit();
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case STRING_LITERAL:
      case LPAREN:
      case LBRACKET:
      case LT:
      case TILDE:{
        ;
        break;
        }
      default:
        jj_la1[22] = jj_gen;
        break label_7;
      }
    }
} catch (Throwable jjte000) {
    if (jjtc000) {
      jjtree.clearNodeScope(jjtn000);
      jjtc000 = false;
    } else {
      jjtree.popNode();
    }
    if (jjte000 instanceof RuntimeException) {
      throw (RuntimeException)jjte000;
    }
    if (jjte000 instanceof ParseException) {
      throw (ParseException)jjte000;
    }
    throw (Error)jjte000;
  } finally {
    if (jjtc000) {
  jjtree.closeNodeScope(jjtn000, jjtree.nodeArity() >1);
  if (jjtree.nodeCreated()) {
   jjtreeCloseNodeScope(jjtn000);
  }
    }
  }
}


  public final void complex_regular_expression_unit() throws ParseException {
 Token t; 
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case STRING_LITERAL:{
      // REStringLiteral
      ASTREStringLiteral jjtn000 = new ASTREStringLiteral(this, NodeType.JJTRESTRINGLITERAL);
      boolean jjtc000 = true;
      jjtree.openNodeScope(jjtn000);
      jjtreeOpenNodeScope(jjtn000);
      try {
      
      StringLiteral();
      } catch (Throwable jjte000) {
        if (jjtc000) {
          jjtree.clearNodeScope(jjtn000);
          jjtc000 = false;
        } else {
          jjtree.popNode();
        }
        if (jjte000 instanceof RuntimeException) {
          throw (RuntimeException)jjte000;
        }
        if (jjte000 instanceof ParseException) {
          throw (ParseException)jjte000;
        }
        throw (Error)jjte000;
      } finally {
        if (jjtc000) {
      jjtree.closeNodeScope(jjtn000, true);
      if (jjtree.nodeCreated()) {
       jjtreeCloseNodeScope(jjtn000);
      }
        }
      }
      break;
      }
    case LT:{
      // REReference
      ASTREReference jjtn001 = new ASTREReference(this, NodeType.JJTREREFERENCE);
      boolean jjtc001 = true;
      jjtree.openNodeScope(jjtn001);
      jjtreeOpenNodeScope(jjtn001);
      try {
      
      jj_consume_token(LT);
      identifier();
      jj_consume_token(GT);
      } catch (Throwable jjte001) {
        if (jjtc001) {
          jjtree.clearNodeScope(jjtn001);
          jjtc001 = false;
        } else {
          jjtree.popNode();
        }
        if (jjte001 instanceof RuntimeException) {
          throw (RuntimeException)jjte001;
        }
        if (jjte001 instanceof ParseException) {
          throw (ParseException)jjte001;
        }
        throw (Error)jjte001;
      } finally {
        if (jjtc001) {
      jjtree.closeNodeScope(jjtn001, true);
      if (jjtree.nodeCreated()) {
       jjtreeCloseNodeScope(jjtn001);
      }
        }
      }
      break;
      }
    case LBRACKET:
    case TILDE:{
      character_list();
      break;
      }
    case LPAREN:{
      t = jj_consume_token(LPAREN);
      complex_regular_expression_choices();
      jj_consume_token(RPAREN);
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case PLUS:{
        // #REOneOrMore(1)
        ASTREOneOrMore jjtn002 = new ASTREOneOrMore(this, NodeType.JJTREONEORMORE);
        boolean jjtc002 = true;
        jjtree.openNodeScope(jjtn002);
        jjtreeOpenNodeScope(jjtn002);
        try {
        
        jj_consume_token(PLUS);
        } finally {
          if (jjtc002) {
        jjtree.closeNodeScope(jjtn002, 1);
        if (jjtree.nodeCreated()) {
         jjtreeCloseNodeScope(jjtn002);
        }
          }
        }
        break;
        }
      case STAR:{
        // #REZeroOrMore(1)
        ASTREZeroOrMore jjtn003 = new ASTREZeroOrMore(this, NodeType.JJTREZEROORMORE);
        boolean jjtc003 = true;
        jjtree.openNodeScope(jjtn003);
        jjtreeOpenNodeScope(jjtn003);
        try {
        
        jj_consume_token(STAR);
        } finally {
          if (jjtc003) {
        jjtree.closeNodeScope(jjtn003, 1);
        if (jjtree.nodeCreated()) {
         jjtreeCloseNodeScope(jjtn003);
        }
          }
        }
        break;
        }
      case HOOK:{
        // #REZeroOrOne(1)
        ASTREZeroOrOne jjtn004 = new ASTREZeroOrOne(this, NodeType.JJTREZEROORONE);
        boolean jjtc004 = true;
        jjtree.openNodeScope(jjtn004);
        jjtreeOpenNodeScope(jjtn004);
        try {
        
        jj_consume_token(HOOK);
        } finally {
          if (jjtc004) {
        jjtree.closeNodeScope(jjtn004, 1);
        if (jjtree.nodeCreated()) {
         jjtreeCloseNodeScope(jjtn004);
        }
          }
        }
        break;
        }
      case LBRACE:{
        jj_consume_token(LBRACE);
        IntegerLiteral();
        switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
        case COMMA:{
          jj_consume_token(COMMA);
          switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
          case INTEGER_LITERAL:{
            IntegerLiteral();
            break;
            }
          default:
            jj_la1[23] = jj_gen;
            ;
          }
          break;
          }
        default:
          jj_la1[24] = jj_gen;
          ;
        }
        // #RRepetitionRange(1)
        ASTRRepetitionRange jjtn005 = new ASTRRepetitionRange(this, NodeType.JJTRREPETITIONRANGE);
        boolean jjtc005 = true;
        jjtree.openNodeScope(jjtn005);
        jjtreeOpenNodeScope(jjtn005);
        try {
        
        jj_consume_token(RBRACE);
        } finally {
          if (jjtc005) {
        jjtree.closeNodeScope(jjtn005, 1);
        if (jjtree.nodeCreated()) {
         jjtreeCloseNodeScope(jjtn005);
        }
          }
        }
        break;
        }
      default:
        jj_la1[25] = jj_gen;
        // #REParenthesized(1)
        ASTREParenthesized jjtn006 = new ASTREParenthesized(this, NodeType.JJTREPARENTHESIZED);
        boolean jjtc006 = true;
        jjtree.openNodeScope(jjtn006);
        jjtreeOpenNodeScope(jjtn006);
        try {
        

jjtree.closeNodeScope(jjtn006, 1);
      jjtc006 = false;
      if (jjtree.nodeCreated()) {
       jjtreeCloseNodeScope(jjtn006);
      }
        } finally {
          if (jjtc006) {
        jjtree.closeNodeScope(jjtn006, 1);
        if (jjtree.nodeCreated()) {
         jjtreeCloseNodeScope(jjtn006);
        }
          }
        }
      }
 ((ASTNode)jjtree.peekNode()).setFirstToken(t); 
      break;
      }
    default:
      jj_la1[26] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
}


  public final void character_list() throws ParseException {  // RECharList
  ASTRECharList jjtn000 = new ASTRECharList(this, NodeType.JJTRECHARLIST);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);
  jjtreeOpenNodeScope(jjtn000);
  try {

    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case TILDE:{
      jj_consume_token(TILDE);
      break;
      }
    default:
      jj_la1[27] = jj_gen;
      ;
    }
    jj_consume_token(LBRACKET);
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case STRING_LITERAL:{
      character_descriptor();
      label_8:
      while (true) {
        switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
        case COMMA:{
          ;
          break;
          }
        default:
          jj_la1[28] = jj_gen;
          break label_8;
        }
        jj_consume_token(COMMA);
        character_descriptor();
      }
      break;
      }
    default:
      jj_la1[29] = jj_gen;
      ;
    }
    jj_consume_token(RBRACKET);
} catch (Throwable jjte000) {
    if (jjtc000) {
      jjtree.clearNodeScope(jjtn000);
      jjtc000 = false;
    } else {
      jjtree.popNode();
    }
    if (jjte000 instanceof RuntimeException) {
      throw (RuntimeException)jjte000;
    }
    if (jjte000 instanceof ParseException) {
      throw (ParseException)jjte000;
    }
    throw (Error)jjte000;
  } finally {
    if (jjtc000) {
  jjtree.closeNodeScope(jjtn000, true);
  if (jjtree.nodeCreated()) {
   jjtreeCloseNodeScope(jjtn000);
  }
    }
  }
}


  public final void character_descriptor() throws ParseException {  // CharDescriptor
  ASTCharDescriptor jjtn000 = new ASTCharDescriptor(this, NodeType.JJTCHARDESCRIPTOR);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);
  jjtreeOpenNodeScope(jjtn000);
  try {

    StringLiteral();
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case MINUS:{
      jj_consume_token(MINUS);
      StringLiteral();
      break;
      }
    default:
      jj_la1[30] = jj_gen;
      ;
    }
} catch (Throwable jjte000) {
    if (jjtc000) {
      jjtree.clearNodeScope(jjtn000);
      jjtc000 = false;
    } else {
      jjtree.popNode();
    }
    if (jjte000 instanceof RuntimeException) {
      throw (RuntimeException)jjte000;
    }
    if (jjte000 instanceof ParseException) {
      throw (ParseException)jjte000;
    }
    throw (Error)jjte000;
  } finally {
    if (jjtc000) {
  jjtree.closeNodeScope(jjtn000, true);
  if (jjtree.nodeCreated()) {
   jjtreeCloseNodeScope(jjtn000);
  }
    }
  }
}


  public final                     Token identifier() throws ParseException {
 Token t; 
    t = jj_consume_token(IDENTIFIER);
 return t; 
}


  public final                Token value() throws ParseException {
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case INTEGER_LITERAL:{
      jj_consume_token(INTEGER_LITERAL);
      break;
      }
    case FALSE:{
      jj_consume_token(FALSE);
      break;
      }
    case TRUE:{
      jj_consume_token(TRUE);
      break;
      }
    default:
      jj_la1[31] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
 return token; 
}


/**********************************************
 * THE JJTREE PRODUCTIONS START HERE       *
 **********************************************/
  public final 
                         ASTNodeDescriptor node_descriptor() throws ParseException {  // NodeDescriptor
  ASTNodeDescriptor jjtn000 = new ASTNodeDescriptor(this, NodeType.JJTNODEDESCRIPTOR);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);
  jjtreeOpenNodeScope(jjtn000);
  try {


    Token t = null;
    String s = null;

    jj_consume_token(HASH);
    s = TypeParameter();
 jjtn000.setName(s); 
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case LPAREN:{
      jj_consume_token(LPAREN);
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case GT:{
        jj_consume_token(GT);
 jjtn000.setGreaterThan(); 
        break;
        }
      default:
        jj_la1[32] = jj_gen;
        ;
      }
      t = value();
 jjtn000.setExpressionText(t.image); 
      jj_consume_token(RPAREN);
      break;
      }
    default:
      jj_la1[33] = jj_gen;
      ;
    }
jjtree.closeNodeScope(jjtn000, true);
  jjtc000 = false;
  if (jjtree.nodeCreated()) {
   jjtreeCloseNodeScope(jjtn000);
  }

  return jjtn000;

} catch (Throwable jjte000) {
    if (jjtc000) {
      jjtree.clearNodeScope(jjtn000);
      jjtc000 = false;
    } else {
      jjtree.popNode();
    }
    if (jjte000 instanceof RuntimeException) {
      throw (RuntimeException)jjte000;
    }
    if (jjte000 instanceof ParseException) {
      throw (ParseException)jjte000;
    }
    throw (Error)jjte000;
  } finally {
    if (jjtc000) {
  jjtree.closeNodeScope(jjtn000, true);
  if (jjtree.nodeCreated()) {
   jjtreeCloseNodeScope(jjtn000);
  }
    }
  }
}


/**********************************************
 * THE JAVA GRAMMAR SPECIFICATION STARTS HERE *
 **********************************************/

/*
 * The following production defines Java identifiers - it
 * includes the reserved words of JavaCC also.
 */
  public final 
                       String TypeParameter() throws ParseException {
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case IDENTIFIER:{
      jj_consume_token(IDENTIFIER);
      break;
      }
    case _LOOKAHEAD:{
      jj_consume_token(_LOOKAHEAD);
      break;
      }
    case _IGNORE_CASE:{
      jj_consume_token(_IGNORE_CASE);
      break;
      }
    case _PARSER:{
      jj_consume_token(_PARSER);
      break;
      }
    case _TOKEN:{
      jj_consume_token(_TOKEN);
      break;
      }
    case _SPECIAL_TOKEN:{
      jj_consume_token(_SPECIAL_TOKEN);
      break;
      }
    case _MORE:{
      jj_consume_token(_MORE);
      break;
      }
    case _SKIP:{
      jj_consume_token(_SKIP);
      break;
      }
    case _EOF:{
      jj_consume_token(_EOF);
      break;
      }
    default:
      jj_la1[34] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
 return token.image; 
}


/*
 * Program structuring syntax follows.
 */
  public final void TypeParameters() throws ParseException {
    jj_consume_token(LT);
    TypeParameter();
    label_9:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case COMMA:{
        ;
        break;
        }
      default:
        jj_la1[35] = jj_gen;
        break label_9;
      }
      jj_consume_token(COMMA);
      TypeParameter();
    }
    jj_consume_token(GT);
}


  public final void FormalParameter() throws ParseException {
    Type();
    TypeParameter();
}


/*
 * Type, name and expression syntax follows.
 */
  public final void Type() throws ParseException {
    if (jj_2_5(2)) {
      TypeParameter();
    } else {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case BOOLEAN:
      case INT:
      case CHAR:{
        PrimitiveType();
        break;
        }
      default:
        jj_la1[36] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
    }
}


  public final void PrimitiveType() throws ParseException {
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case BOOLEAN:{
      jj_consume_token(BOOLEAN);
      break;
      }
    case CHAR:{
      jj_consume_token(CHAR);
      break;
      }
    case INT:{
      jj_consume_token(INT);
      break;
      }
    default:
      jj_la1[37] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
}


/*
 * Expression syntax follows.
 */
  public final void Expression() throws ParseException {  // Expression
  ASTExpression jjtn000 = new ASTExpression(this, NodeType.JJTEXPRESSION);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);
  jjtreeOpenNodeScope(jjtn000);
  try {

    PrimaryPrefix();
    label_10:
    while (true) {
      if (jj_2_6(2)) {
        ;
      } else {
        break label_10;
      }
      PrimarySuffix();
    }
} catch (Throwable jjte000) {
    if (jjtc000) {
      jjtree.clearNodeScope(jjtn000);
      jjtc000 = false;
    } else {
      jjtree.popNode();
    }
    if (jjte000 instanceof RuntimeException) {
      throw (RuntimeException)jjte000;
    }
    if (jjte000 instanceof ParseException) {
      throw (ParseException)jjte000;
    }
    throw (Error)jjte000;
  } finally {
    if (jjtc000) {
  jjtree.closeNodeScope(jjtn000, true);
  if (jjtree.nodeCreated()) {
   jjtreeCloseNodeScope(jjtn000);
  }
    }
  }
}


  public final void PrimaryPrefix() throws ParseException {
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case NULL:
    case TRUE:
    case FALSE:
    case INTEGER_LITERAL:
    case FLOATING_POINT_LITERAL:
    case CHARACTER_LITERAL:
    case STRING_LITERAL:{
      Literal();
      break;
      }
    case LPAREN:{
      jj_consume_token(LPAREN);
      Expression();
      jj_consume_token(RPAREN);
      break;
      }
    case _LOOKAHEAD:
    case _IGNORE_CASE:
    case _PARSER:
    case _TOKEN:
    case _SPECIAL_TOKEN:
    case _MORE:
    case _SKIP:
    case _EOF:
    case IDENTIFIER:{
      TypeParameter();
      break;
      }
    default:
      jj_la1[38] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
}


  public final void PrimarySuffix() throws ParseException {
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case LBRACKET:{
      jj_consume_token(LBRACKET);
      Expression();
      jj_consume_token(RBRACKET);
      break;
      }
    case LPAREN:{
      Arguments();
      break;
      }
    default:
      jj_la1[39] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
}


  public final void Literal() throws ParseException {
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case NULL:{
      jj_consume_token(NULL);
      break;
      }
    case INTEGER_LITERAL:{
      jj_consume_token(INTEGER_LITERAL);
      break;
      }
    case FLOATING_POINT_LITERAL:{
      jj_consume_token(FLOATING_POINT_LITERAL);
      break;
      }
    case CHARACTER_LITERAL:{
      jj_consume_token(CHARACTER_LITERAL);
      break;
      }
    case STRING_LITERAL:{
      jj_consume_token(STRING_LITERAL);
      break;
      }
    case TRUE:
    case FALSE:{
      BooleanLiteral();
      break;
      }
    default:
      jj_la1[40] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
}


  public final void IntegerLiteral() throws ParseException {
    jj_consume_token(INTEGER_LITERAL);
}


  public final void BooleanLiteral() throws ParseException {
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case TRUE:{
      jj_consume_token(TRUE);
      break;
      }
    case FALSE:{
      jj_consume_token(FALSE);
      break;
      }
    default:
      jj_la1[41] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
}


  public final void StringLiteral() throws ParseException {
    jj_consume_token(STRING_LITERAL);
}


/*
 * Parsing this fills "tokens" with all tokens of the arguments
 * excluding the parentheses at each end.
 */
  public final void Arguments() throws ParseException {
    jj_consume_token(LPAREN);
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case _LOOKAHEAD:
    case _IGNORE_CASE:
    case _PARSER:
    case _TOKEN:
    case _SPECIAL_TOKEN:
    case _MORE:
    case _SKIP:
    case _EOF:
    case NULL:
    case TRUE:
    case FALSE:
    case INTEGER_LITERAL:
    case FLOATING_POINT_LITERAL:
    case CHARACTER_LITERAL:
    case STRING_LITERAL:
    case LPAREN:
    case IDENTIFIER:{
      ArgumentList();
      break;
      }
    default:
      jj_la1[42] = jj_gen;
      ;
    }
    jj_consume_token(RPAREN);
}


  public final void ArgumentList() throws ParseException {
    Expression();
    label_11:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case COMMA:{
        ;
        break;
        }
      default:
        jj_la1[43] = jj_gen;
        break label_11;
      }
      jj_consume_token(COMMA);
      Expression();
    }
}


/*
 * Statement syntax follows.
 * Parsing this fills "tokens" with all tokens of the block
 * excluding the braces at each end.
 */
  public final void Statement() throws ParseException {
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case ECODE_DATA:{
      jj_consume_token(ECODE_DATA);
      jj_consume_token(ECODE_END);
      break;
      }
    case LBRACE:{
      jj_consume_token(LBRACE);
      label_12:
      while (true) {
        switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
        case ECODE_DATA:
        case LBRACE:{
          ;
          break;
          }
        default:
          jj_la1[44] = jj_gen;
          break label_12;
        }
        Statement();
      }
      jj_consume_token(RBRACE);
      break;
      }
    default:
      jj_la1[45] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
}


  private boolean jj_2_1(int xla) {
    jj_la = xla;
    jj_lastpos = jj_scanpos = token;
    try {
      return (!jj_3_1());
    } catch (LookaheadSuccess ls) {
      return true;
    } finally {
      jj_save(0, xla);
    }
  }


  private boolean jj_2_2(int xla) {
    jj_la = xla;
    jj_lastpos = jj_scanpos = token;
    try {
      return (!jj_3_2());
    } catch (LookaheadSuccess ls) {
      return true;
    } finally {
      jj_save(1, xla);
    }
  }


  private boolean jj_2_3(int xla) {
    jj_la = xla;
    jj_lastpos = jj_scanpos = token;
    try {
      return (!jj_3_3());
    } catch (LookaheadSuccess ls) {
      return true;
    } finally {
      jj_save(2, xla);
    }
  }


  private boolean jj_2_4(int xla) {
    jj_la = xla;
    jj_lastpos = jj_scanpos = token;
    try {
      return (!jj_3_4());
    } catch (LookaheadSuccess ls) {
      return true;
    } finally {
      jj_save(3, xla);
    }
  }


  private boolean jj_2_5(int xla) {
    jj_la = xla;
    jj_lastpos = jj_scanpos = token;
    try {
      return (!jj_3_5());
    } catch (LookaheadSuccess ls) {
      return true;
    } finally {
      jj_save(4, xla);
    }
  }


  private boolean jj_2_6(int xla) {
    jj_la = xla;
    jj_lastpos = jj_scanpos = token;
    try {
      return (!jj_3_6());
    } catch (LookaheadSuccess ls) {
      return true;
    } finally {
      jj_save(5, xla);
    }
  }


  private boolean jj_3R_null_3() {
    if (jj_3R_Expression_1())
      return true;
    if (jj_scan_token(ParserConstants.ASSIGN))
      return true;
    return false;
  }


  private boolean jj_3R_complex_regular_expression_unit_25() {
    if (jj_scan_token(ParserConstants.LPAREN))
      return true;
    if (jj_3R_complex_regular_expression_choices_5())
      return true;
    return false;
  }


  private boolean jj_3_5() {
    if (jj_3R_TypeParameter_7())
      return true;
    return false;
  }


  private boolean jj_3R_complex_regular_expression_unit_24() {
    if (jj_3R_character_list_28())
      return true;
    return false;
  }


  private boolean jj_3R_complex_regular_expression_unit_23() {
    if (jj_scan_token(ParserConstants.LT))
      return true;
    if (jj_3R_identifier_6())
      return true;
    return false;
  }


  private boolean jj_3R_complex_regular_expression_17() {
    if (jj_3R_complex_regular_expression_unit_20())
      return true;
    return false;
  }


  private boolean jj_3R_complex_regular_expression_unit_20() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_scan_token(STRING_LITERAL)) {
      jj_scanpos = xsp;
    if (jj_3R_complex_regular_expression_unit_23()) {
      jj_scanpos = xsp;
    if (jj_3R_complex_regular_expression_unit_24()) {
      jj_scanpos = xsp;
    if (jj_3R_complex_regular_expression_unit_25())
      return true;
    }
    }
    }
    return false;
  }


  private boolean jj_3R_complex_regular_expression_10() {
    Token xsp;
    if (jj_3R_complex_regular_expression_17()) return true;
    while (true) {
      xsp = jj_scanpos;
      if (jj_3R_complex_regular_expression_17()) { jj_scanpos = xsp; break; }
    }
    return false;
  }


  private boolean jj_3R_regular_expression_4() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_scan_token(HASH)) jj_scanpos = xsp;
    if (jj_3R_identifier_6())
      return true;
    if (jj_scan_token(ParserConstants.COLON))
      return true;
    return false;
  }


  private boolean jj_3R_complex_regular_expression_choices_5() {
    if (jj_3R_complex_regular_expression_10())
      return true;
    Token xsp;
    while (true) {
      xsp = jj_scanpos;
      if (jj_3R_complex_regular_expression_choices_11()) { jj_scanpos = xsp; break; }
    }
    return false;
  }


  private boolean jj_3_4() {
    if (jj_scan_token(ParserConstants.LT))
      return true;
    if (jj_3R_identifier_6())
      return true;
    return false;
  }



  private boolean jj_3_3() {
    if (jj_scan_token(ParserConstants.LT))
      return true;
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_regular_expression_4()) jj_scanpos = xsp;
    if (jj_3R_complex_regular_expression_choices_5())
      return true;
    if (jj_scan_token(ParserConstants.GT))
      return true;
    return false;
  }







  private boolean jj_3R_ArgumentList_30() {
    if (jj_scan_token(ParserConstants.COMMA))
      return true;
    if (jj_3R_Expression_1())
      return true;
    return false;
  }





  private boolean jj_3R_BooleanLiteral_27() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_scan_token(TRUE)) {
      jj_scanpos = xsp;
    if (jj_scan_token(FALSE))
      return true;
    }
    return false;
  }


  private boolean jj_3R_TypeParameter_7() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_scan_token(IDENTIFIER)) {
      jj_scanpos = xsp;
    if (jj_scan_token(_LOOKAHEAD)) {
      jj_scanpos = xsp;
    if (jj_scan_token(_IGNORE_CASE)) {
      jj_scanpos = xsp;
    if (jj_scan_token(_PARSER)) {
      jj_scanpos = xsp;
    if (jj_scan_token(_TOKEN)) {
      jj_scanpos = xsp;
    if (jj_scan_token(_SPECIAL_TOKEN)) {
      jj_scanpos = xsp;
    if (jj_scan_token(_MORE)) {
      jj_scanpos = xsp;
    if (jj_scan_token(_SKIP)) {
      jj_scanpos = xsp;
    if (jj_scan_token(_EOF))
      return true;
    }
    }
    }
    }
    }
    }
    }
    }
    return false;
  }


  private boolean jj_3R_Arguments_21() {
    if (jj_3R_ArgumentList_26())
      return true;
    return false;
  }


  private boolean jj_3_1() {
    if (jj_3R_Expression_1())
      return true;
    if (jj_scan_token(ParserConstants.ASSIGN))
      return true;
    return false;
  }


  private boolean jj_3_2() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_null_2()) {
      jj_scanpos = xsp;
    if (jj_scan_token(STRING_LITERAL)) {
      jj_scanpos = xsp;
    if (jj_scan_token(LT)) {
      jj_scanpos = xsp;
    if (jj_3R_null_3())
      return true;
    }
    }
    }
    return false;
  }


  private boolean jj_3R_null_2() {
    if (jj_3R_identifier_6())
      return true;
    return false;
  }


  private boolean jj_3R_ArgumentList_26() {
    if (jj_3R_Expression_1())
      return true;
    Token xsp;
    while (true) {
      xsp = jj_scanpos;
      if (jj_3R_ArgumentList_30()) { jj_scanpos = xsp; break; }
    }
    return false;
  }


  private boolean jj_3R_Arguments_18() {
    if (jj_scan_token(ParserConstants.LPAREN))
      return true;
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_Arguments_21()) jj_scanpos = xsp;
    if (jj_scan_token(ParserConstants.RPAREN))
      return true;
    return false;
  }


  private boolean jj_3R_character_list_29() {
    if (jj_3R_character_descriptor_31())
      return true;
    return false;
  }


  private boolean jj_3R_Literal_22() {
    if (jj_3R_BooleanLiteral_27())
      return true;
    return false;
  }


  private boolean jj_3_6() {
    if (jj_3R_PrimarySuffix_8())
      return true;
    return false;
  }


  private boolean jj_3R_Literal_19() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_scan_token(NULL)) {
      jj_scanpos = xsp;
    if (jj_scan_token(INTEGER_LITERAL)) {
      jj_scanpos = xsp;
    if (jj_scan_token(FLOATING_POINT_LITERAL)) {
      jj_scanpos = xsp;
    if (jj_scan_token(CHARACTER_LITERAL)) {
      jj_scanpos = xsp;
    if (jj_scan_token(STRING_LITERAL)) {
      jj_scanpos = xsp;
    if (jj_3R_Literal_22())
      return true;
    }
    }
    }
    }
    }
    return false;
  }


  private boolean jj_3R_PrimarySuffix_13() {
    if (jj_3R_Arguments_18())
      return true;
    return false;
  }


  private boolean jj_3R_PrimarySuffix_8() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_PrimarySuffix_12()) {
      jj_scanpos = xsp;
    if (jj_3R_PrimarySuffix_13())
      return true;
    }
    return false;
  }


  private boolean jj_3R_PrimarySuffix_12() {
    if (jj_scan_token(ParserConstants.LBRACKET))
      return true;
    if (jj_3R_Expression_1())
      return true;
    if (jj_scan_token(ParserConstants.RBRACKET))
      return true;
    return false;
  }


  private boolean jj_3R_identifier_6() {
    if (jj_scan_token(ParserConstants.IDENTIFIER))
      return true;
    return false;
  }


  private boolean jj_3R_PrimaryPrefix_16() {
    if (jj_3R_TypeParameter_7())
      return true;
    return false;
  }


  private boolean jj_3R_PrimaryPrefix_15() {
    if (jj_scan_token(ParserConstants.LPAREN))
      return true;
    if (jj_3R_Expression_1())
      return true;
    if (jj_scan_token(ParserConstants.RPAREN))
      return true;
    return false;
  }


  private boolean jj_3R_complex_regular_expression_choices_11() {
    if (jj_scan_token(ParserConstants.BIT_OR))
      return true;
    return false;
  }


  private boolean jj_3R_PrimaryPrefix_9() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_PrimaryPrefix_14()) {
      jj_scanpos = xsp;
    if (jj_3R_PrimaryPrefix_15()) {
      jj_scanpos = xsp;
    if (jj_3R_PrimaryPrefix_16())
      return true;
    }
    }
    return false;
  }


  private boolean jj_3R_PrimaryPrefix_14() {
    if (jj_3R_Literal_19())
      return true;
    return false;
  }


  private boolean jj_3R_character_descriptor_31() {
    if (jj_scan_token(STRING_LITERAL))
      return true;
    return false;
  }


  private boolean jj_3R_Expression_1() {
    if (jj_3R_PrimaryPrefix_9())
      return true;
    Token xsp;
    while (true) {
      xsp = jj_scanpos;
      if (jj_3_6()) { jj_scanpos = xsp; break; }
    }
    return false;
  }


  private boolean jj_3R_character_list_28() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_scan_token(TILDE)) jj_scanpos = xsp;
    if (jj_scan_token(ParserConstants.LBRACKET))
      return true;
    xsp = jj_scanpos;
    if (jj_3R_character_list_29()) jj_scanpos = xsp;
    if (jj_scan_token(ParserConstants.RBRACKET))
      return true;
    return false;
  }



  /** Generated Token Manager. */
  public Lexer               token_source;
  /** Current token. */
  public Token token;
  /** Next token. */
  public Token               jj_nt;
  private int                jj_ntk;
  private Token              jj_scanpos, jj_lastpos;
  private int                jj_la;
  private int                jj_gen;
  private final int[]        jj_la1    = new int[46];
  private static final int[] jj_la1_0  = { 0x0, 0x100, 0x38000000, 0x0, 0x38002fe, 0x0, 0x0, 0x0, 0x2, 0x0, 0x20000000, 0x3c0002fe, 0x0, 0x0, 0x0, 0x200002, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x20000000, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x38000000, 0x0, 0x0, 0x2fe, 0x0, 0x3800000, 0x3800000, 0x3c0002fe, 0x0, 0x3c000000, 0x18000000, 0x3c0002fe, 0x0, 0x200000, 0x200000};
  private static final int[] jj_la1_1  = { 0x4000, 0x0, 0x80, 0x4000, 0x40000000, 0x2000000, 0x1000000, 0x20000000, 0x0, 0x1000000, 0x0, 0x400001c2, 0x20000, 0x40100080, 0x14800000, 0x1400, 0x100, 0x1000000, 0x41000000, 0x80, 0x100000, 0x20000000, 0x501180, 0x0, 0x4000, 0x14800400, 0x501180, 0x400000, 0x4000, 0x80, 0x8000000, 0x0, 0x80000, 0x100, 0x40000000, 0x4000, 0x0, 0x0, 0x400001c2, 0x1100, 0xc2, 0x0, 0x400001c2, 0x4000, 0x400, 0x400};
  private static final int[] jj_la1_2  = { 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0};
  private final JJCalls[]    jj_2_rtns = new JJCalls[6];
  private boolean            jj_rescan = false;
  private int                jj_gc     = 0;

  /** Constructor. */
  public Parser(Provider stream) {
    this(new Lexer(new JavaCharStream(stream)));
  }

  /** Constructor. */
  public Parser(String dsl) throws ParseException, TokenException {
    this(new StringProvider(dsl));
  }

  /** Constructor with generated Token Manager. */
  public Parser(Lexer tm) {
    token_source = tm;
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 46; i++)
      jj_la1[i] = -1;
    for (int i = 0; i < jj_2_rtns.length; i++)
      jj_2_rtns[i] = new JJCalls();
  }

  /** Reinitialise. */
  public void ReInit(Lexer tm) {
    token_source = tm;
    token = new Token();
    jj_ntk = -1;
    jjtree.reset();
    jj_gen = 0;
    for (int i = 0; i < 46; i++)
      jj_la1[i] = -1;
    for (int i = 0; i < jj_2_rtns.length; i++)
      jj_2_rtns[i] = new JJCalls();
  }

  private Token jj_consume_token(int kind) throws ParseException {
    Token oldToken;
    if ((oldToken = token).next != null)
      token = token.next;
    else
      token = token.next = token_source.getNextToken();
    jj_ntk = -1;
    if (token.kind == kind) {
      jj_gen++;
      if (++jj_gc > 100) {
        jj_gc = 0;
        for (int i = 0; i < jj_2_rtns.length; i++) {
          JJCalls c = jj_2_rtns[i];
          while (c != null) {
            if (c.gen < jj_gen)
              c.first = null;
            c = c.next;
          }
        }
      }
      return this.token;
    }
    this.token = oldToken;
    this.jj_kind = kind;
    throw generateParseException();
  }

  @SuppressWarnings("serial")
  static private final class LookaheadSuccess extends java.lang.RuntimeException {
    @Override
    public Throwable fillInStackTrace() {
      return this;
    }
  }
  static private final LookaheadSuccess jj_ls = new LookaheadSuccess();
  private boolean jj_scan_token(int kind) {
    if (jj_scanpos == jj_lastpos) {
      jj_la--;
      if (jj_scanpos.next == null) {
        jj_lastpos = jj_scanpos = jj_scanpos.next = token_source.getNextToken();
      } else {
        jj_lastpos = jj_scanpos = jj_scanpos.next;
      }
    } else {
      jj_scanpos = jj_scanpos.next;
    }
    if (jj_rescan) {
      int i = 0;
      Token tok = token;
      while (tok != null && tok != jj_scanpos) {
        i++;
        tok = tok.next;
      }
      if (tok != null)
        jj_add_error_token(kind, i);
    }
    if (jj_scanpos.kind != kind)
      return true;
    if (jj_la == 0 && jj_scanpos == jj_lastpos)
      throw Parser.jj_ls;
    return false;
  }


  /** Get the next Token. */
  final public Token getNextToken() {
    if (token.next != null)
      token = token.next;
    else
      token = token.next = token_source.getNextToken();
      jj_ntk = -1;
    jj_gen++;
    return this.token;
  }

  /** Get the specific Token. */
  final public Token getToken(int index) {
    Token t = this.token;
    for (int i = 0; i < index; i++) {
      if (t.next != null)
        t = t.next;
      else
        t = t.next = token_source.getNextToken();
    }
    return t;
  }

  private int jj_ntk_f() {
    if ((jj_nt=token.next) == null)
      return (jj_ntk = (token.next=token_source.getNextToken()).kind);
    else
      return (jj_ntk = jj_nt.kind);
  }

  private final java.util.List<int[]> jj_expentries = new java.util.ArrayList<>();
  private int[]                       jj_expentry;
  private int                         jj_kind       = -1;
  private final int[]                 jj_lasttokens = new int[100];
  private int                         jj_endpos;

  private void jj_add_error_token(int kind, int pos) {
    if (pos >= 100) {
      return;
    }

    if (pos == (this.jj_endpos + 1)) {
      this.jj_lasttokens[this.jj_endpos++] = kind;
    } else if (this.jj_endpos != 0) {
      this.jj_expentry = new int[this.jj_endpos];

      for (int i = 0; i < this.jj_endpos; i++) {
        this.jj_expentry[i] = this.jj_lasttokens[i];
      }

      for (int[] oldentry : this.jj_expentries) {
        if (oldentry.length == this.jj_expentry.length) {
          boolean isMatched = true;

          for (int i = 0; i < this.jj_expentry.length; i++) {
            if (oldentry[i] != this.jj_expentry[i]) {
              isMatched = false;
              break;
            }

          }
          if (isMatched) {
            this.jj_expentries.add(this.jj_expentry);
            break;
          }
        }
      }

      if (pos != 0) {
        this.jj_lasttokens[(this.jj_endpos = pos) - 1] = kind;
      }
    }
  }

    /**
     * Generate ParseException.
     */
    public ParseException generateParseException() {
        this.jj_expentries.clear();
        boolean[] la1tokens = new boolean[65];
        if (this.jj_kind >= 0) {
            la1tokens[this.jj_kind] = true;
            this.jj_kind = -1;
        }
        for (int i = 0; i < 46; i++) {
            if (this.jj_la1[i] == this.jj_gen) {
                for (int j = 0; j < 32; j++) {
                    if ((Parser.jj_la1_0[i] & (1 << j)) != 0) {
                        la1tokens[j] = true;
                    }
                    if ((Parser.jj_la1_1[i] & (1 << j)) != 0) {
                        la1tokens[32 + j] = true;
                    }
                    if ((Parser.jj_la1_2[i] & (1 << j)) != 0) {
                        la1tokens[64 + j] = true;
                    }
                }
            }
        }
        for (int i = 0; i < 65; i++) {
            if (la1tokens[i]) {
                this.jj_expentry = new int[1];
                this.jj_expentry[0] = i;
                this.jj_expentries.add(this.jj_expentry);
            }
        }
        this.jj_endpos = 0;
        jj_rescan_token();
        jj_add_error_token(0, 0);
        int[][] exptokseq = new int[this.jj_expentries.size()][];
        for (int i = 0; i < this.jj_expentries.size(); i++) {
            exptokseq[i] = this.jj_expentries.get(i);
        }

        return new ParseException(this.token, exptokseq, ParserConstants.tokenImage,
            this.token_source == null ? null : Lexer.lexStateNames[this.token_source.curLexState]);
    }

    private boolean trace_enabled;

    /**
     * Trace enabled.
     */
    final public boolean trace_enabled() {
        return this.trace_enabled;
    }

    /**
     * Enable tracing.
     */
    final public void enable_tracing() {
    }

    /**
     * Disable tracing.
     */
    final public void disable_tracing() {
    }

    private void jj_rescan_token() {
        this.jj_rescan = true;
        for (int i = 0; i < 6; i++) {
            try {
                JJCalls p = this.jj_2_rtns[i];

                do {
                    if (p.gen > this.jj_gen) {
                        this.jj_la = p.arg;
                        this.jj_lastpos = this.jj_scanpos = p.first;
                        switch (i) {
                            case 0:
                                jj_3_1();
                                break;
                            case 1:
                                jj_3_2();
                                break;
                            case 2:
                                jj_3_3();
                                break;
                            case 3:
                                jj_3_4();
                                break;
                            case 4:
                                jj_3_5();
                                break;
                            case 5:
                                jj_3_6();
                                break;
                        }
                    }
                    p = p.next;
                } while (p != null);
            } catch (LookaheadSuccess ls) {
            }
        }
        this.jj_rescan = false;
    }

    private void jj_save(int index, int xla) {
        JJCalls p = this.jj_2_rtns[index];
        while (p.gen > this.jj_gen) {
            if (p.next == null) {
                p = p.next = new JJCalls();
                break;
            }
            p = p.next;
        }

        p.gen = (this.jj_gen + xla) - this.jj_la;
        p.first = this.token;
        p.arg = xla;
    }

    static final class JJCalls {

        int     gen;
        Token   first;
        int     arg;
        JJCalls next;
    }


    protected final Node rootNode() {
        return this.jjtree.rootNode();
    }

    protected void jjtreeOpenNodeScope(Node node) throws ParseException {
    }

    protected void jjtreeCloseNodeScope(Node node) throws ParseException {
    }
}

// Checksum=36C10F259F80EDA683F0596D4629BEF1 (Do not edit this line!)
// Options: BASE_PARSER='ASTParser', CACHE_TOKENS=false, DEBUG_LOOKAHEAD=false, DEBUG_PARSER=false, DEPTH_LIMIT=0, ERROR_REPORTING=true, EXPANSIONS=46, EXPANSIONS_PHASE, JAVA_IMPORTS=1, JAVA_IMPORTS_VALUE, JAVA_PACKAGE='org.hivevm.cc.jjtree', JJ2_INDEX=6, JJ2_OFFSET=6, JJ2_OFFSET_INDEX, JJ2_OFFSET_VALUE, LOOKAHEADS=6, LOOKAHEADS_PHASE, LOOKAHEAD_NEEDED=false, MASK_INDEX=46, NORMALPRODUCTIONS=31, NORMALPRODUCTIONS_PHASE, TOKEN_COUNT=65, TOKEN_MASKS=3, TOKEN_MASKS_INDEX, TOKEN_MASKS_LA1=3, TOKEN_MASKS_LA1_INDEX, TOKEN_MASKS_LA1_VALUE, TOKEN_MASKS_MASK, USE_AST=true
