// Generated by HiveVM CC v.1.0 - Do not edit this line!

package org.hivevm.cc.parser;

import java.io.Closeable;
import java.io.IOException;

public interface Provider extends Closeable {

    /**
     * Reads characters into an array
     */
    int read(char[] buffer, int offset, int length) throws IOException;
}
// Checksum=0EA922B8AC443C44CCA715DAA0E0760B (Do not edit this line!)
// Options: JAVA_PACKAGE='org.hivevm.cc.parser'
