// Generated by HiveVM CC v.1.0 - Do not edit this line!

package org.hivevm.cc.parser;

import java.io.IOException;

public class StringProvider implements Provider {

    private       String _string;
    private final int    _size;
    private       int    _position;

    public StringProvider(String string) {
        this._string = string;
        this._size = string.length();
        this._position = 0;
    }

    @Override
    public int read(char[] cbuf, int off, int len) throws IOException {
        int numCharsOutstandingInString = this._size - this._position;

        if (numCharsOutstandingInString == 0) {
            return -1;
        }

        int numBytesInBuffer = cbuf.length;
        int numBytesToRead = numBytesInBuffer - off;
        numBytesToRead = numBytesToRead > len ? len : numBytesToRead;

        if (numBytesToRead > numCharsOutstandingInString) {
            numBytesToRead = numCharsOutstandingInString;
        }

        this._string.getChars(this._position, this._position + numBytesToRead, cbuf, off);

        this._position += numBytesToRead;

        return numBytesToRead;
    }

    @Override
    public void close() throws IOException {
        this._string = null;
    }
}
// Checksum=3308154071853523A06F8A0F5E2656AA (Do not edit this line!)
// Options: JAVA_PACKAGE='org.hivevm.cc.parser'
