// Generated by HiveVM CC v.1.0 - Do not edit this line!

package org.hivevm.cc.jjtree;

public class ASTBNFNonTerminal extends ASTNode {

    public ASTBNFNonTerminal(Parser p, int id) {
        super(p, id);
    }

    public Object jjtAccept(NodeVisitor visitor, ASTWriter data) {
        return visitor.visit(this, data);
    }
}
// Checksum=3A1AA3F5F0142132587D6340790C0FE0 (Do not edit this line!)
// Options: JAVA_PACKAGE='org.hivevm.cc.jjtree', NODE_CLASS='ASTNode', NODE_FACTORY='', NODE_TYPE='ASTBNFNonTerminal', VISITOR=true, VISITOR_DATA_TYPE='ASTWriter', VISITOR_EXCEPTION='', VISITOR_RETURN_TYPE='Object', VISITOR_RETURN_TYPE_VOID=false
