// Generated by HiveVM CC v.1.0 - Do not edit this line!

package org.hivevm.cc.jjtree;

public class ASTBNFNodeScope extends ASTNode {

    public ASTBNFNodeScope(Parser p, int id) {
        super(p, id);
    }

    public Object jjtAccept(NodeVisitor visitor, ASTWriter data) {
        return visitor.visit(this, data);
    }
}
// Checksum=7B6A764D84CD9BC0CD55A4AD5F8FD87F (Do not edit this line!)
// Options: JAVA_PACKAGE='org.hivevm.cc.jjtree', NODE_CLASS='ASTNode', NODE_FACTORY='', NODE_TYPE='ASTBNFNodeScope', VISITOR=true, VISITOR_DATA_TYPE='ASTWriter', VISITOR_EXCEPTION='', VISITOR_RETURN_TYPE='Object', VISITOR_RETURN_TYPE_VOID=false
