// Generated by HiveVM CC v.1.0 - Do not edit this line!

package org.hivevm.cc.jjtree;

public class ASTRESequence extends ASTNode {

    public ASTRESequence(Parser p, int id) {
        super(p, id);
    }

    public Object jjtAccept(NodeVisitor visitor, ASTWriter data) {
        return visitor.visit(this, data);
    }
}
// Checksum=E83171E8E4A9AF45703AA086181A2837 (Do not edit this line!)
// Options: JAVA_PACKAGE='org.hivevm.cc.jjtree', NODE_CLASS='ASTNode', NODE_FACTORY='', NODE_TYPE='ASTRESequence', VISITOR=true, VISITOR_DATA_TYPE='ASTWriter', VISITOR_EXCEPTION='', VISITOR_RETURN_TYPE='Object', VISITOR_RETURN_TYPE_VOID=false
