// Generated by HiveVM CC v.1.0 - Do not edit this line!

package org.hivevm.cc.jjtree;

public class ASTREParenthesized extends ASTNode {

    public ASTREParenthesized(Parser p, int id) {
        super(p, id);
    }

    public Object jjtAccept(NodeVisitor visitor, ASTWriter data) {
        return visitor.visit(this, data);
    }
}
// Checksum=31BBFBB29CD6A0C3AFCAB4FC5092B857 (Do not edit this line!)
// Options: JAVA_PACKAGE='org.hivevm.cc.jjtree', NODE_CLASS='ASTNode', NODE_FACTORY='', NODE_TYPE='ASTREParenthesized', VISITOR=true, VISITOR_DATA_TYPE='ASTWriter', VISITOR_EXCEPTION='', VISITOR_RETURN_TYPE='Object', VISITOR_RETURN_TYPE_VOID=false
