// Generated by HiveVM CC v.1.0 - Do not edit this line!

package org.hivevm.cc.jjtree;

import java.io.Closeable;
import java.io.IOException;

public interface Provider extends Closeable {

    /**
     * Reads characters into an array
     */
    int read(char[] buffer, int offset, int length) throws IOException;
}
// Checksum=3F50E1F40371ED005FF049E232A147C5 (Do not edit this line!)
// Options: JAVA_PACKAGE='org.hivevm.cc.jjtree'
